/** \file
 *  This C source file was generated by $ANTLR version 3.1.1
 *
 *     -  From the grammar source file : hammer_sema.gt
 *     -                            On : 2017-09-22 21:36:30
 *     -           for the tree parser : hammer_semaTreeParser *
 * Editing it, at least manually, is not wise. 
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/

/* =============================================================================
 * This is what the grammar programmer asked us to put at the top of every file.
 */


#include <hammer/sema/actions.h>
#include <hammer/parscore/identifier.h>
#include <hammer/ast/requirement_set.h>
#include <hammer/ast/requirement.h>
#include <hammer/ast/path_like_seq.h>
#include <hammer/ast/feature.h>

#define SEMA static_cast<const hammer::sema::actions*>(PARSER->super)
#define DECLARE_TYPE(Type, name) Type name ( Type ::allocator_type{SEMA->get_context()});

/* End of Header action.
 * =============================================================================
 */
/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "hammer_sema.h"
/* ----------------------------------------- */





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */
 
#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   phammer_sema_##scope##_SCOPE
#define SCOPE_STACK(scope)  phammer_sema_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->phammer_sema_##scope##Top
#define	SCOPE_SIZE(scope)			(ctx->SCOPE_STACK(scope)->size(ctx->SCOPE_STACK(scope)))
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

/* Macros for accessing things in the parser
 */
 
#undef	    PARSER
#undef	    RECOGNIZER		    
#undef	    HAVEPARSEDRULE
#undef	    INPUT
#undef	    STRSTREAM
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    MATCHT
#undef	    MATCHANYT
#undef	    FOLLOWSTACK
#undef	    FOLLOWPUSH
#undef	    FOLLOWPOP
#undef	    PRECOVER
#undef	    PREPORTERROR
#undef	    LA
#undef	    LT
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    PERRORRECOVERY
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    RECOVERFROMMISMATCHEDSET
#undef	    RECOVERFROMMISMATCHEDELEMENT
#undef	    BACKTRACKING
#undef      ADAPTOR
#undef	    RULEMEMO		
#undef		SEEK    
#undef		INDEX
#undef		DBG

#define	    PARSER							ctx->pTreeParser  
#define	    RECOGNIZER						PARSER->rec
#define		PSRSTATE						RECOGNIZER->state
#define	    HAVEPARSEDRULE(r)				RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define	    INPUT							PARSER->ctnstream
#define		ISTREAM							INPUT->tnstream->istream
#define	    STRSTREAM						INPUT->tnstream
#define	    HASEXCEPTION()					(PSRSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION						PSRSTATE->exception
#define	    MATCHT(t, fs)					RECOGNIZER->match(RECOGNIZER, t, fs)
#define	    MATCHANYT()						RECOGNIZER->matchAny(RECOGNIZER)
#define	    FOLLOWSTACK					    PSRSTATE->following
#define	    FOLLOWPUSH(x)					FOLLOWSTACK->push(FOLLOWSTACK, ((void *)(&(x))), NULL)
#define	    FOLLOWPOP()						FOLLOWSTACK->pop(FOLLOWSTACK)
#define	    PRECOVER()						RECOGNIZER->recover(RECOGNIZER)
#define	    PREPORTERROR()					RECOGNIZER->reportError(RECOGNIZER)
#define	    LA(n)							ISTREAM->_LA(ISTREAM, n)
#define	    LT(n)							INPUT->tnstream->_LT(INPUT->tnstream, n)
#define	    CONSTRUCTEX()					RECOGNIZER->exConstruct(RECOGNIZER)
#define	    CONSUME()						ISTREAM->consume(ISTREAM)
#define	    MARK()							ISTREAM->mark(ISTREAM)
#define	    REWIND(m)						ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()					ISTREAM->rewindLast(ISTREAM)
#define	    PERRORRECOVERY					PSRSTATE->errorRecovery
#define	    FAILEDFLAG						PSRSTATE->failed
#define	    HASFAILED()						(FAILEDFLAG == ANTLR3_TRUE)
#define	    BACKTRACKING					PSRSTATE->backtracking
#define	    RECOVERFROMMISMATCHEDSET(s)		RECOGNIZER->recoverFromMismatchedSet(RECOGNIZER, s)
#define	    RECOVERFROMMISMATCHEDELEMENT(e)	RECOGNIZER->recoverFromMismatchedElement(RECOGNIZER, s)
#define     ADAPTOR                         INPUT->adaptor
#define		RULEMEMO						PSRSTATE->ruleMemo
#define		SEEK(n)							ISTREAM->seek(ISTREAM, n)
#define		INDEX()							ISTREAM->index(ISTREAM)
#define		DBG								RECOGNIZER->debugger


#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */



/** \brief Table of all token names in symbolic order, mainly used for
 *         error reporting.
 */
pANTLR3_UINT8   hammer_semaTokenNames[45+4]
     = {
        (pANTLR3_UINT8) "<invalid>",       /* String to print to indicate an invalid token */
        (pANTLR3_UINT8) "<EOR>",
        (pANTLR3_UINT8) "<DOWN>", 
        (pANTLR3_UINT8) "<UP>", 
        (pANTLR3_UINT8) "Hamfile",
        (pANTLR3_UINT8) "Rule",
        (pANTLR3_UINT8) "Local",
        (pANTLR3_UINT8) "Explicit",
        (pANTLR3_UINT8) "Arguments",
        (pANTLR3_UINT8) "EmptyArgument",
        (pANTLR3_UINT8) "NamedArgument",
        (pANTLR3_UINT8) "Structure",
        (pANTLR3_UINT8) "StructureField",
        (pANTLR3_UINT8) "List",
        (pANTLR3_UINT8) "Feature",
        (pANTLR3_UINT8) "ConditionalFeature",
        (pANTLR3_UINT8) "RuleInvocation",
        (pANTLR3_UINT8) "Path",
        (pANTLR3_UINT8) "Target",
        (pANTLR3_UINT8) "Wildcard",
        (pANTLR3_UINT8) "FeatureLogicalAnd",
        (pANTLR3_UINT8) "FeatureLogicalOr",
        (pANTLR3_UINT8) "WS",
        (pANTLR3_UINT8) "Id",
        (pANTLR3_UINT8) "Slash",
        (pANTLR3_UINT8) "DoubleSlash",
        (pANTLR3_UINT8) "PublicTag",
        (pANTLR3_UINT8) "QuestionMark",
        (pANTLR3_UINT8) "Asterix",
        (pANTLR3_UINT8) "STRING",
        (pANTLR3_UINT8) "STRING_1",
        (pANTLR3_UINT8) "STRING_ID",
        (pANTLR3_UINT8) "STRING_ID1",
        (pANTLR3_UINT8) "COMMENT",
        (pANTLR3_UINT8) "';'",
        (pANTLR3_UINT8) "':'",
        (pANTLR3_UINT8) "'='",
        (pANTLR3_UINT8) "'{'",
        (pANTLR3_UINT8) "'}'",
        (pANTLR3_UINT8) "'<'",
        (pANTLR3_UINT8) "'>'",
        (pANTLR3_UINT8) "'('",
        (pANTLR3_UINT8) "')'",
        (pANTLR3_UINT8) "'->'",
        (pANTLR3_UINT8) "'||'",
        (pANTLR3_UINT8) "'&&'",
        (pANTLR3_UINT8) "'['",
        (pANTLR3_UINT8) "']'",
        (pANTLR3_UINT8) "Public"
       };

        

// Forward declare the locally static matching functions we have generated.
//
static const hammer::ast::hamfile*	hamfile    (phammer_sema ctx);
static void	statement    (phammer_sema ctx, hammer::ast::statements_t* statements);
static const hammer::ast::expression*	target_def_or_rule_call    (phammer_sema ctx);
static void	arguments    (phammer_sema ctx, hammer::ast::expressions_t* args);
static const hammer::ast::expression*	argument    (phammer_sema ctx);
static const hammer::ast::expression*	named_expression    (phammer_sema ctx);
static const hammer::ast::expression*	expression    (phammer_sema ctx);
static const hammer::ast::expression*	expression_a    (phammer_sema ctx);
static void	list_of    (phammer_sema ctx, hammer::ast::expressions_t* args);
static const hammer::ast::expression*	list_element    (phammer_sema ctx);
static const hammer::ast::expression*	path    (phammer_sema ctx);
static void	path_impl    (phammer_sema ctx, std::pair<pANTLR3_COMMON_TOKEN, pANTLR3_COMMON_TOKEN>* bounds);
static pANTLR3_COMMON_TOKEN	path_element    (phammer_sema ctx);
static pANTLR3_COMMON_TOKEN	wildcard    (phammer_sema ctx);
static pANTLR3_COMMON_TOKEN	wildcard_elem    (phammer_sema ctx);
static void	public_tag    (phammer_sema ctx, hammer::parscore::source_location* tag_loc);
static const hammer::ast::expression*	rule_invocation    (phammer_sema ctx);
static const hammer::ast::expression*	feature    (phammer_sema ctx);
static const hammer::ast::expression*	feature_value    (phammer_sema ctx);
static void	hammer_semaFree(phammer_sema ctx);
/* For use in tree output where we are accumulating rule labels via label += ruleRef
 * we need a function that knows how to free a return scope when the list is destroyed. 
 * We cannot just use ANTLR3_FREE because in debug tracking mode, this is a macro.
 */
static	void ANTLR3_CDECL freeScope(void * scope)
{
    ANTLR3_FREE(scope);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "hammer_sema.gt";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}
/** \brief Create a new hammer_sema parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API phammer_sema
hammer_semaNew   (pANTLR3_COMMON_TREE_NODE_STREAM instream)
{
	// See if we can create a new parser with the standard constructor
	//
	return hammer_semaNewSSD(instream, NULL);
}

/** \brief Create a new hammer_sema parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API phammer_sema
hammer_semaNewSSD   (pANTLR3_COMMON_TREE_NODE_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    phammer_sema ctx;	    /* Context structure we will build and return   */
    
    ctx	= (phammer_sema) ANTLR3_CALLOC(1, sizeof(hammer_sema));
    
    if	(ctx == NULL)
    {
		// Failed to allocate memory for parser context
		//
        return  NULL;
    }
    
    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * the base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 parser function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function. 
     *
     * We don't use the macros defined in hammer_sema.h here, in order that you can get a sense
     * of what goes where.
     */

    /* Create a base Tree parser/recognizer, using the supplied tree node stream
     */
    ctx->pTreeParser		= antlr3TreeParserNewStream(ANTLR3_SIZE_HINT, instream, state);
    /* Install the implementation of our hammer_sema interface
     */
    ctx->hamfile	= hamfile;
    ctx->statement	= statement;
    ctx->target_def_or_rule_call	= target_def_or_rule_call;
    ctx->arguments	= arguments;
    ctx->argument	= argument;
    ctx->named_expression	= named_expression;
    ctx->expression	= expression;
    ctx->expression_a	= expression_a;
    ctx->list_of	= list_of;
    ctx->list_element	= list_element;
    ctx->path	= path;
    ctx->path_impl	= path_impl;
    ctx->path_element	= path_element;
    ctx->wildcard	= wildcard;
    ctx->wildcard_elem	= wildcard_elem;
    ctx->public_tag	= public_tag;
    ctx->rule_invocation	= rule_invocation;
    ctx->feature	= feature;
    ctx->feature_value	= feature_value;
    ctx->free			= hammer_semaFree;
    ctx->getGrammarFileName	= getGrammarFileName;
    
    /* Install the scope pushing methods.
     */

        
    

	
    /* Install the token table
     */
    PSRSTATE->tokenNames   = hammer_semaTokenNames;
    
    
    /* Return the newly built parser to the caller
     */
    return  ctx;
}

/** Free the parser resources
 */
 static void
 hammer_semaFree(phammer_sema ctx)
 {
    /* Free any scope memory
     */
    
        
	// Free this parser
	//
    ctx->pTreeParser->free(ctx->pTreeParser);
    ANTLR3_FREE(ctx);

    /* Everything is released, so we can return
     */
    return;
 }
 
/** Return token names used by this tree parser
 *
 * The returned pointer is used as an index into the token names table (using the token 
 * number as the index).
 * 
 * \return Pointer to first char * in the table.
 */
static pANTLR3_UINT8    *getTokenNames() 
{
        return hammer_semaTokenNames; 
}

    
/* Declare the bitsets
 */

/** Bitset defining follow set for error recovery in rule state: FOLLOW_Hamfile_in_hamfile81  */
static	ANTLR3_BITWORD FOLLOW_Hamfile_in_hamfile81_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000004) };
static  ANTLR3_BITSET_LIST FOLLOW_Hamfile_in_hamfile81	= { FOLLOW_Hamfile_in_hamfile81_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_statement_in_hamfile83  */
static	ANTLR3_BITWORD FOLLOW_statement_in_hamfile83_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000028) };
static  ANTLR3_BITSET_LIST FOLLOW_statement_in_hamfile83	= { FOLLOW_statement_in_hamfile83_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_target_def_or_rule_call_in_statement115  */
static	ANTLR3_BITWORD FOLLOW_target_def_or_rule_call_in_statement115_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_target_def_or_rule_call_in_statement115	= { FOLLOW_target_def_or_rule_call_in_statement115_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_Rule_in_target_def_or_rule_call138  */
static	ANTLR3_BITWORD FOLLOW_Rule_in_target_def_or_rule_call138_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000004) };
static  ANTLR3_BITSET_LIST FOLLOW_Rule_in_target_def_or_rule_call138	= { FOLLOW_Rule_in_target_def_or_rule_call138_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_Id_in_target_def_or_rule_call142  */
static	ANTLR3_BITWORD FOLLOW_Id_in_target_def_or_rule_call142_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000100) };
static  ANTLR3_BITSET_LIST FOLLOW_Id_in_target_def_or_rule_call142	= { FOLLOW_Id_in_target_def_or_rule_call142_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_arguments_in_target_def_or_rule_call144  */
static	ANTLR3_BITWORD FOLLOW_arguments_in_target_def_or_rule_call144_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000008) };
static  ANTLR3_BITSET_LIST FOLLOW_arguments_in_target_def_or_rule_call144	= { FOLLOW_arguments_in_target_def_or_rule_call144_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_Arguments_in_arguments162  */
static	ANTLR3_BITWORD FOLLOW_Arguments_in_arguments162_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000004) };
static  ANTLR3_BITSET_LIST FOLLOW_Arguments_in_arguments162	= { FOLLOW_Arguments_in_arguments162_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_argument_in_arguments165  */
static	ANTLR3_BITWORD FOLLOW_argument_in_arguments165_bits[]	= { ANTLR3_UINT64_LIT(0x0000000004836628) };
static  ANTLR3_BITSET_LIST FOLLOW_argument_in_arguments165	= { FOLLOW_argument_in_arguments165_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_EmptyArgument_in_argument192  */
static	ANTLR3_BITWORD FOLLOW_EmptyArgument_in_argument192_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_EmptyArgument_in_argument192	= { FOLLOW_EmptyArgument_in_argument192_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expression_in_argument199  */
static	ANTLR3_BITWORD FOLLOW_expression_in_argument199_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_expression_in_argument199	= { FOLLOW_expression_in_argument199_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_named_expression_in_argument206  */
static	ANTLR3_BITWORD FOLLOW_named_expression_in_argument206_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_named_expression_in_argument206	= { FOLLOW_named_expression_in_argument206_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_NamedArgument_in_named_expression223  */
static	ANTLR3_BITWORD FOLLOW_NamedArgument_in_named_expression223_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000004) };
static  ANTLR3_BITSET_LIST FOLLOW_NamedArgument_in_named_expression223	= { FOLLOW_NamedArgument_in_named_expression223_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_Id_in_named_expression225  */
static	ANTLR3_BITWORD FOLLOW_Id_in_named_expression225_bits[]	= { ANTLR3_UINT64_LIT(0x0000000004836028) };
static  ANTLR3_BITSET_LIST FOLLOW_Id_in_named_expression225	= { FOLLOW_Id_in_named_expression225_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expression_in_named_expression227  */
static	ANTLR3_BITWORD FOLLOW_expression_in_named_expression227_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000008) };
static  ANTLR3_BITSET_LIST FOLLOW_expression_in_named_expression227	= { FOLLOW_expression_in_named_expression227_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_list_of_in_expression252  */
static	ANTLR3_BITWORD FOLLOW_list_of_in_expression252_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_list_of_in_expression252	= { FOLLOW_list_of_in_expression252_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_rule_invocation_in_expression263  */
static	ANTLR3_BITWORD FOLLOW_rule_invocation_in_expression263_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_rule_invocation_in_expression263	= { FOLLOW_rule_invocation_in_expression263_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_feature_in_expression270  */
static	ANTLR3_BITWORD FOLLOW_feature_in_expression270_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_feature_in_expression270	= { FOLLOW_feature_in_expression270_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_PublicTag_in_expression278  */
static	ANTLR3_BITWORD FOLLOW_PublicTag_in_expression278_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000004) };
static  ANTLR3_BITSET_LIST FOLLOW_PublicTag_in_expression278	= { FOLLOW_PublicTag_in_expression278_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_feature_in_expression280  */
static	ANTLR3_BITWORD FOLLOW_feature_in_expression280_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000008) };
static  ANTLR3_BITSET_LIST FOLLOW_feature_in_expression280	= { FOLLOW_feature_in_expression280_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_target_def_or_rule_call_in_expression288  */
static	ANTLR3_BITWORD FOLLOW_target_def_or_rule_call_in_expression288_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_target_def_or_rule_call_in_expression288	= { FOLLOW_target_def_or_rule_call_in_expression288_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_path_in_expression295  */
static	ANTLR3_BITWORD FOLLOW_path_in_expression295_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_path_in_expression295	= { FOLLOW_path_in_expression295_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_Id_in_expression302  */
static	ANTLR3_BITWORD FOLLOW_Id_in_expression302_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_Id_in_expression302	= { FOLLOW_Id_in_expression302_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_List_in_list_of334  */
static	ANTLR3_BITWORD FOLLOW_List_in_list_of334_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000004) };
static  ANTLR3_BITSET_LIST FOLLOW_List_in_list_of334	= { FOLLOW_List_in_list_of334_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_list_element_in_list_of337  */
static	ANTLR3_BITWORD FOLLOW_list_element_in_list_of337_bits[]	= { ANTLR3_UINT64_LIT(0x0000000004834008) };
static  ANTLR3_BITSET_LIST FOLLOW_list_element_in_list_of337	= { FOLLOW_list_element_in_list_of337_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_rule_invocation_in_list_element373  */
static	ANTLR3_BITWORD FOLLOW_rule_invocation_in_list_element373_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_rule_invocation_in_list_element373	= { FOLLOW_rule_invocation_in_list_element373_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_path_in_list_element380  */
static	ANTLR3_BITWORD FOLLOW_path_in_list_element380_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_path_in_list_element380	= { FOLLOW_path_in_list_element380_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_feature_in_list_element387  */
static	ANTLR3_BITWORD FOLLOW_feature_in_list_element387_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_feature_in_list_element387	= { FOLLOW_feature_in_list_element387_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_PublicTag_in_list_element395  */
static	ANTLR3_BITWORD FOLLOW_PublicTag_in_list_element395_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000004) };
static  ANTLR3_BITSET_LIST FOLLOW_PublicTag_in_list_element395	= { FOLLOW_PublicTag_in_list_element395_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_feature_in_list_element397  */
static	ANTLR3_BITWORD FOLLOW_feature_in_list_element397_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000008) };
static  ANTLR3_BITSET_LIST FOLLOW_feature_in_list_element397	= { FOLLOW_feature_in_list_element397_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_Id_in_list_element405  */
static	ANTLR3_BITWORD FOLLOW_Id_in_list_element405_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_Id_in_list_element405	= { FOLLOW_Id_in_list_element405_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_Path_in_path427  */
static	ANTLR3_BITWORD FOLLOW_Path_in_path427_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000004) };
static  ANTLR3_BITSET_LIST FOLLOW_Path_in_path427	= { FOLLOW_Path_in_path427_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_path_impl_in_path429  */
static	ANTLR3_BITWORD FOLLOW_path_impl_in_path429_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000008) };
static  ANTLR3_BITSET_LIST FOLLOW_path_impl_in_path429	= { FOLLOW_path_impl_in_path429_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_Slash_in_path_impl446  */
static	ANTLR3_BITWORD FOLLOW_Slash_in_path_impl446_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000880000) };
static  ANTLR3_BITSET_LIST FOLLOW_Slash_in_path_impl446	= { FOLLOW_Slash_in_path_impl446_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_path_element_in_path_impl448  */
static	ANTLR3_BITWORD FOLLOW_path_element_in_path_impl448_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000880000) };
static  ANTLR3_BITSET_LIST FOLLOW_path_element_in_path_impl448	= { FOLLOW_path_element_in_path_impl448_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_path_element_in_path_impl453  */
static	ANTLR3_BITWORD FOLLOW_path_element_in_path_impl453_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_path_element_in_path_impl453	= { FOLLOW_path_element_in_path_impl453_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_path_element_in_path_impl462  */
static	ANTLR3_BITWORD FOLLOW_path_element_in_path_impl462_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000880000) };
static  ANTLR3_BITSET_LIST FOLLOW_path_element_in_path_impl462	= { FOLLOW_path_element_in_path_impl462_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_path_element_in_path_impl464  */
static	ANTLR3_BITWORD FOLLOW_path_element_in_path_impl464_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000880000) };
static  ANTLR3_BITSET_LIST FOLLOW_path_element_in_path_impl464	= { FOLLOW_path_element_in_path_impl464_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_path_element_in_path_impl469  */
static	ANTLR3_BITWORD FOLLOW_path_element_in_path_impl469_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_path_element_in_path_impl469	= { FOLLOW_path_element_in_path_impl469_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_Id_in_path_element485  */
static	ANTLR3_BITWORD FOLLOW_Id_in_path_element485_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_Id_in_path_element485	= { FOLLOW_Id_in_path_element485_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_wildcard_in_path_element492  */
static	ANTLR3_BITWORD FOLLOW_wildcard_in_path_element492_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_wildcard_in_path_element492	= { FOLLOW_wildcard_in_path_element492_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_Wildcard_in_wildcard509  */
static	ANTLR3_BITWORD FOLLOW_Wildcard_in_wildcard509_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000004) };
static  ANTLR3_BITSET_LIST FOLLOW_Wildcard_in_wildcard509	= { FOLLOW_Wildcard_in_wildcard509_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_wildcard_elem_in_wildcard511  */
static	ANTLR3_BITWORD FOLLOW_wildcard_elem_in_wildcard511_bits[]	= { ANTLR3_UINT64_LIT(0x0000000018800000) };
static  ANTLR3_BITSET_LIST FOLLOW_wildcard_elem_in_wildcard511	= { FOLLOW_wildcard_elem_in_wildcard511_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_wildcard_elem_in_wildcard516  */
static	ANTLR3_BITWORD FOLLOW_wildcard_elem_in_wildcard516_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000008) };
static  ANTLR3_BITSET_LIST FOLLOW_wildcard_elem_in_wildcard516	= { FOLLOW_wildcard_elem_in_wildcard516_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_Id_in_wildcard_elem534  */
static	ANTLR3_BITWORD FOLLOW_Id_in_wildcard_elem534_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_Id_in_wildcard_elem534	= { FOLLOW_Id_in_wildcard_elem534_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_QuestionMark_in_wildcard_elem541  */
static	ANTLR3_BITWORD FOLLOW_QuestionMark_in_wildcard_elem541_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_QuestionMark_in_wildcard_elem541	= { FOLLOW_QuestionMark_in_wildcard_elem541_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_Asterix_in_wildcard_elem548  */
static	ANTLR3_BITWORD FOLLOW_Asterix_in_wildcard_elem548_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_Asterix_in_wildcard_elem548	= { FOLLOW_Asterix_in_wildcard_elem548_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_Public_in_public_tag563  */
static	ANTLR3_BITWORD FOLLOW_Public_in_public_tag563_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_Public_in_public_tag563	= { FOLLOW_Public_in_public_tag563_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_RuleInvocation_in_rule_invocation586  */
static	ANTLR3_BITWORD FOLLOW_RuleInvocation_in_rule_invocation586_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000004) };
static  ANTLR3_BITSET_LIST FOLLOW_RuleInvocation_in_rule_invocation586	= { FOLLOW_RuleInvocation_in_rule_invocation586_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_Id_in_rule_invocation590  */
static	ANTLR3_BITWORD FOLLOW_Id_in_rule_invocation590_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000100) };
static  ANTLR3_BITSET_LIST FOLLOW_Id_in_rule_invocation590	= { FOLLOW_Id_in_rule_invocation590_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_arguments_in_rule_invocation592  */
static	ANTLR3_BITWORD FOLLOW_arguments_in_rule_invocation592_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000008) };
static  ANTLR3_BITSET_LIST FOLLOW_arguments_in_rule_invocation592	= { FOLLOW_arguments_in_rule_invocation592_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_Feature_in_feature611  */
static	ANTLR3_BITWORD FOLLOW_Feature_in_feature611_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000004) };
static  ANTLR3_BITSET_LIST FOLLOW_Feature_in_feature611	= { FOLLOW_Feature_in_feature611_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_Id_in_feature613  */
static	ANTLR3_BITWORD FOLLOW_Id_in_feature613_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000820000) };
static  ANTLR3_BITSET_LIST FOLLOW_Id_in_feature613	= { FOLLOW_Id_in_feature613_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_feature_value_in_feature615  */
static	ANTLR3_BITWORD FOLLOW_feature_value_in_feature615_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000008) };
static  ANTLR3_BITSET_LIST FOLLOW_feature_value_in_feature615	= { FOLLOW_feature_value_in_feature615_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_Id_in_feature_value633  */
static	ANTLR3_BITWORD FOLLOW_Id_in_feature_value633_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_Id_in_feature_value633	= { FOLLOW_Id_in_feature_value633_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_path_in_feature_value640  */
static	ANTLR3_BITWORD FOLLOW_path_in_feature_value640_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_path_in_feature_value640	= { FOLLOW_path_in_feature_value640_bits, 1	};
     


/* =========================================================================
 * DFA tables for the parser
 */
/** Static dfa state tables for Cyclic dfa:
 *    ()+ loopback of 92:10: ( path_element )+
 */
static const ANTLR3_INT32 dfa7_eot[10] =
    {
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1
    };
static const ANTLR3_INT32 dfa7_eof[10] =
    {
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1
    };
static const ANTLR3_INT32 dfa7_min[10] =
    {
	19, 3, 2, -1, -1, 23, 3, 3, 3, 3
    };
static const ANTLR3_INT32 dfa7_max[10] =
    {
	23, 23, 2, -1, -1, 28, 28, 28, 28, 23
    };
static const ANTLR3_INT32 dfa7_accept[10] =
    {
	-1, -1, -1, 1, 2, -1, -1, -1, -1, -1
    };
static const ANTLR3_INT32 dfa7_special[10] =
    {	
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1
    };

/** Used when there is no transition table entry for a particular state */
#define dfa7_T_empty	    NULL

static const ANTLR3_INT32 dfa7_T0[] =
    {
	6, -1, -1, -1, 7, 8
    };static const ANTLR3_INT32 dfa7_T1[] =
    {
	5
    };static const ANTLR3_INT32 dfa7_T2[] =
    {
	9, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, 6, -1, -1, -1, 7, 8
    };static const ANTLR3_INT32 dfa7_T3[] =
    {
	2, -1, -1, -1, 1
    };static const ANTLR3_INT32 dfa7_T4[] =
    {
	4, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 3, -1, -1, 
	-1, 3
    };

/* Transition tables are a table of sub tables, with some tables
 * reused for efficiency.
 */
static const ANTLR3_INT32 * const dfa7_transitions[] =
{
    dfa7_T3, dfa7_T4, dfa7_T1, dfa7_T_empty, dfa7_T_empty, dfa7_T0, dfa7_T2, 
    dfa7_T2, dfa7_T2, dfa7_T4	
};


/* Declare tracking structure for Cyclic DFA 7
 */
static
ANTLR3_CYCLIC_DFA cdfa7
    =	{
	    7,		    /* Decision number of this dfa	    */
	    /* Which decision this represents:   */
	    (const pANTLR3_UCHAR)"()+ loopback of 92:10: ( path_element )+",	
	    (CDFA_SPECIAL_FUNC) antlr3dfaspecialStateTransition,	/* Default special state transition function	*/
	    antlr3dfaspecialTransition,		/* DFA specialTransition is currently just a default function in the runtime */
	    antlr3dfapredict,			/* DFA simulator function is in the runtime */
	    dfa7_eot,	    /* EOT table			    */
	    dfa7_eof,	    /* EOF table			    */
	    dfa7_min,	    /* Minimum tokens for each state    */
	    dfa7_max,	    /* Maximum tokens for each state    */
	    dfa7_accept,	/* Accept table			    */
	    dfa7_special,	/* Special transition states	    */
	    dfa7_transitions	/* Table of transition tables	    */

	};	    
/* End of Cyclic DFA 7
 * ---------------------
 *//** Static dfa state tables for Cyclic dfa:
 *    ()* loopback of 93:23: ( path_element )*
 */
static const ANTLR3_INT32 dfa8_eot[10] =
    {
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1
    };
static const ANTLR3_INT32 dfa8_eof[10] =
    {
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1
    };
static const ANTLR3_INT32 dfa8_min[10] =
    {
	19, 3, 2, -1, -1, 23, 3, 3, 3, 3
    };
static const ANTLR3_INT32 dfa8_max[10] =
    {
	23, 23, 2, -1, -1, 28, 28, 28, 28, 23
    };
static const ANTLR3_INT32 dfa8_accept[10] =
    {
	-1, -1, -1, 2, 1, -1, -1, -1, -1, -1
    };
static const ANTLR3_INT32 dfa8_special[10] =
    {	
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1
    };

/** Used when there is no transition table entry for a particular state */
#define dfa8_T_empty	    NULL

static const ANTLR3_INT32 dfa8_T0[] =
    {
	3, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 4, -1, -1, 
	-1, 4
    };static const ANTLR3_INT32 dfa8_T1[] =
    {
	6, -1, -1, -1, 7, 8
    };static const ANTLR3_INT32 dfa8_T2[] =
    {
	2, -1, -1, -1, 1
    };static const ANTLR3_INT32 dfa8_T3[] =
    {
	5
    };static const ANTLR3_INT32 dfa8_T4[] =
    {
	9, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, 6, -1, -1, -1, 7, 8
    };

/* Transition tables are a table of sub tables, with some tables
 * reused for efficiency.
 */
static const ANTLR3_INT32 * const dfa8_transitions[] =
{
    dfa8_T2, dfa8_T0, dfa8_T3, dfa8_T_empty, dfa8_T_empty, dfa8_T1, dfa8_T4, 
    dfa8_T4, dfa8_T4, dfa8_T0	
};


/* Declare tracking structure for Cyclic DFA 8
 */
static
ANTLR3_CYCLIC_DFA cdfa8
    =	{
	    8,		    /* Decision number of this dfa	    */
	    /* Which decision this represents:   */
	    (const pANTLR3_UCHAR)"()* loopback of 93:23: ( path_element )*",	
	    (CDFA_SPECIAL_FUNC) antlr3dfaspecialStateTransition,	/* Default special state transition function	*/
	    antlr3dfaspecialTransition,		/* DFA specialTransition is currently just a default function in the runtime */
	    antlr3dfapredict,			/* DFA simulator function is in the runtime */
	    dfa8_eot,	    /* EOT table			    */
	    dfa8_eof,	    /* EOF table			    */
	    dfa8_min,	    /* Minimum tokens for each state    */
	    dfa8_max,	    /* Maximum tokens for each state    */
	    dfa8_accept,	/* Accept table			    */
	    dfa8_special,	/* Special transition states	    */
	    dfa8_transitions	/* Table of transition tables	    */

	};	    
/* End of Cyclic DFA 8
 * ---------------------
 */ 
/* =========================================================================
 * End of DFA tables for the parser
 */ 
 
/* ==============================================
 * Parsing rules
 */
/** 
 * $ANTLR start hamfile
 * hammer_sema.gt:22:1: hamfile returns [const hammer::ast::hamfile* result] : ^( Hamfile ( statement[&statements] )* ) ;
 */
static const hammer::ast::hamfile*
hamfile(phammer_sema ctx)
{   
    const hammer::ast::hamfile* result = NULL;

    /* Initialize rule variables
     */


     DECLARE_TYPE(hammer::ast::statements_t, statements); 
    {
        // hammer_sema.gt:24:2: ( ^( Hamfile ( statement[&statements] )* ) )
        // hammer_sema.gt:24:4: ^( Hamfile ( statement[&statements] )* )
        {
             MATCHT(Hamfile, &FOLLOW_Hamfile_in_hamfile81); 
            if  (HASEXCEPTION())
            {
                goto rulehamfileEx;
            }


            if ( LA(1)==ANTLR3_TOKEN_DOWN ) {
                MATCHT(ANTLR3_TOKEN_DOWN, NULL); 
                if  (HASEXCEPTION())
                {
                    goto rulehamfileEx;
                }


                // hammer_sema.gt:24:14: ( statement[&statements] )*

                for (;;)
                {
                    int alt1=2;
                    {
                       /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                        */
                        int LA1_0 = LA(1);
                        if ( (LA1_0 == Rule) ) 
                        {
                            alt1=1;
                        }

                    }
                    switch (alt1) 
                    {
                	case 1:
                	    // hammer_sema.gt:24:14: statement[&statements]
                	    {
                	        FOLLOWPUSH(FOLLOW_statement_in_hamfile83);
                	        statement(ctx, &statements);

                	        FOLLOWPOP();
                	        if  (HASEXCEPTION())
                	        {
                	            goto rulehamfileEx;
                	        }


                	    }
                	    break;

                	default:
                	    goto loop1;	/* break out of the loop */
                	    break;
                    }
                }
                loop1: ; /* Jump out to here if this rule does not match */


                MATCHT(ANTLR3_TOKEN_UP, NULL); 
                if  (HASEXCEPTION())
                {
                    goto rulehamfileEx;
                }

            }
            {
                 result = SEMA->on_hamfile(statements); 
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulehamfileEx; /* Prevent compiler warnings */
    rulehamfileEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return result;
}
/* $ANTLR end hamfile */

/** 
 * $ANTLR start statement
 * hammer_sema.gt:27:1: statement[hammer::ast::statements_t* statements] : target_def_or_rule_call ;
 */
static void
statement(phammer_sema ctx, hammer::ast::statements_t* statements)
{   
    const hammer::ast::expression* target_def_or_rule_call1;
    #undef	RETURN_TYPE_target_def_or_rule_call1
    #define	RETURN_TYPE_target_def_or_rule_call1 const hammer::ast::expression*

    /* Initialize rule variables
     */


    target_def_or_rule_call1 = NULL;

    {
        // hammer_sema.gt:28:2: ( target_def_or_rule_call )
        // hammer_sema.gt:28:4: target_def_or_rule_call
        {
            FOLLOWPUSH(FOLLOW_target_def_or_rule_call_in_statement115);
            target_def_or_rule_call1=target_def_or_rule_call(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulestatementEx;
            }

            {
                 statements->push_back(target_def_or_rule_call1); 
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulestatementEx; /* Prevent compiler warnings */
    rulestatementEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return ;
}
/* $ANTLR end statement */

/** 
 * $ANTLR start target_def_or_rule_call
 * hammer_sema.gt:31:1: target_def_or_rule_call returns [const hammer::ast::expression* result] : ^( Rule name= Id arguments[&args] ) ;
 */
static const hammer::ast::expression*
target_def_or_rule_call(phammer_sema ctx)
{   
    const hammer::ast::expression* result = NULL;

    pANTLR3_BASE_TREE    name;

    /* Initialize rule variables
     */


     DECLARE_TYPE(hammer::ast::expressions_t, args); 
    name       = NULL;

    {
        // hammer_sema.gt:33:2: ( ^( Rule name= Id arguments[&args] ) )
        // hammer_sema.gt:33:4: ^( Rule name= Id arguments[&args] )
        {
             MATCHT(Rule, &FOLLOW_Rule_in_target_def_or_rule_call138); 
            if  (HASEXCEPTION())
            {
                goto ruletarget_def_or_rule_callEx;
            }


            MATCHT(ANTLR3_TOKEN_DOWN, NULL); 
            if  (HASEXCEPTION())
            {
                goto ruletarget_def_or_rule_callEx;
            }

            name = (pANTLR3_BASE_TREE) MATCHT(Id, &FOLLOW_Id_in_target_def_or_rule_call142); 
            if  (HASEXCEPTION())
            {
                goto ruletarget_def_or_rule_callEx;
            }

            FOLLOWPUSH(FOLLOW_arguments_in_target_def_or_rule_call144);
            arguments(ctx, &args);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruletarget_def_or_rule_callEx;
            }


            MATCHT(ANTLR3_TOKEN_UP, NULL); 
            if  (HASEXCEPTION())
            {
                goto ruletarget_def_or_rule_callEx;
            }

            {
                 result = SEMA->on_target_or_rule_call(name->getToken(name), args); 
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruletarget_def_or_rule_callEx; /* Prevent compiler warnings */
    ruletarget_def_or_rule_callEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return result;
}
/* $ANTLR end target_def_or_rule_call */

/** 
 * $ANTLR start arguments
 * hammer_sema.gt:36:1: arguments[hammer::ast::expressions_t* args] : ^( Arguments ( argument )* ) ;
 */
static void
arguments(phammer_sema ctx, hammer::ast::expressions_t* args)
{   
    const hammer::ast::expression* argument2;
    #undef	RETURN_TYPE_argument2
    #define	RETURN_TYPE_argument2 const hammer::ast::expression*

    /* Initialize rule variables
     */


    argument2 = NULL;

    {
        // hammer_sema.gt:37:2: ( ^( Arguments ( argument )* ) )
        // hammer_sema.gt:37:4: ^( Arguments ( argument )* )
        {
             MATCHT(Arguments, &FOLLOW_Arguments_in_arguments162); 
            if  (HASEXCEPTION())
            {
                goto ruleargumentsEx;
            }


            if ( LA(1)==ANTLR3_TOKEN_DOWN ) {
                MATCHT(ANTLR3_TOKEN_DOWN, NULL); 
                if  (HASEXCEPTION())
                {
                    goto ruleargumentsEx;
                }


                // hammer_sema.gt:37:16: ( argument )*

                for (;;)
                {
                    int alt2=2;
                    {
                       /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                        */
                        int LA2_0 = LA(1);
                        if ( (LA2_0 == Rule || ((LA2_0 >= EmptyArgument) && (LA2_0 <= NamedArgument)) || ((LA2_0 >= List) && (LA2_0 <= Feature)) || ((LA2_0 >= RuleInvocation) && (LA2_0 <= Path)) || LA2_0 == Id || LA2_0 == PublicTag) ) 
                        {
                            alt2=1;
                        }

                    }
                    switch (alt2) 
                    {
                	case 1:
                	    // hammer_sema.gt:37:17: argument
                	    {
                	        FOLLOWPUSH(FOLLOW_argument_in_arguments165);
                	        argument2=argument(ctx);

                	        FOLLOWPOP();
                	        if  (HASEXCEPTION())
                	        {
                	            goto ruleargumentsEx;
                	        }

                	        {
                	             args->push_back(argument2); 
                	        }

                	    }
                	    break;

                	default:
                	    goto loop2;	/* break out of the loop */
                	    break;
                    }
                }
                loop2: ; /* Jump out to here if this rule does not match */


                MATCHT(ANTLR3_TOKEN_UP, NULL); 
                if  (HASEXCEPTION())
                {
                    goto ruleargumentsEx;
                }

            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleargumentsEx; /* Prevent compiler warnings */
    ruleargumentsEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return ;
}
/* $ANTLR end arguments */

/** 
 * $ANTLR start argument
 * hammer_sema.gt:40:1: argument returns [const hammer::ast::expression* result] : ( EmptyArgument | expression | named_expression );
 */
static const hammer::ast::expression*
argument(phammer_sema ctx)
{   
    const hammer::ast::expression* result = NULL;

    pANTLR3_BASE_TREE    EmptyArgument3;
    const hammer::ast::expression* expression4;
    #undef	RETURN_TYPE_expression4
    #define	RETURN_TYPE_expression4 const hammer::ast::expression*

    const hammer::ast::expression* named_expression5;
    #undef	RETURN_TYPE_named_expression5
    #define	RETURN_TYPE_named_expression5 const hammer::ast::expression*

    /* Initialize rule variables
     */


    EmptyArgument3       = NULL;
    expression4 = NULL;
    named_expression5 = NULL;

    {
        {
            //  hammer_sema.gt:41:2: ( EmptyArgument | expression | named_expression )
            
            ANTLR3_UINT32 alt3;

            alt3=3;

            switch ( LA(1) ) 
            {
            case EmptyArgument:
            	{
            		alt3=1;
            	}
                break;
            case Rule:
            case List:
            case Feature:
            case RuleInvocation:
            case Path:
            case Id:
            case PublicTag:
            	{
            		alt3=2;
            	}
                break;
            case NamedArgument:
            	{
            		alt3=3;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 3;
                EXCEPTION->state        = 0;


                goto ruleargumentEx;
            }

            switch (alt3) 
            {
        	case 1:
        	    // hammer_sema.gt:41:4: EmptyArgument
        	    {
        	        EmptyArgument3 = (pANTLR3_BASE_TREE) MATCHT(EmptyArgument, &FOLLOW_EmptyArgument_in_argument192); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleargumentEx;
        	        }

        	        {
        	             result = SEMA->on_empty_expr(EmptyArgument3->getToken(EmptyArgument3)); 
        	        }

        	    }
        	    break;
        	case 2:
        	    // hammer_sema.gt:42:4: expression
        	    {
        	        FOLLOWPUSH(FOLLOW_expression_in_argument199);
        	        expression4=expression(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleargumentEx;
        	        }

        	        {
        	             result = expression4; 
        	        }

        	    }
        	    break;
        	case 3:
        	    // hammer_sema.gt:43:4: named_expression
        	    {
        	        FOLLOWPUSH(FOLLOW_named_expression_in_argument206);
        	        named_expression5=named_expression(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleargumentEx;
        	        }

        	        {
        	             result = named_expression5; 
        	        }

        	    }
        	    break;

            }
        }
    }
    

    // This is where rules clean up and exit
    //
    goto ruleargumentEx; /* Prevent compiler warnings */
    ruleargumentEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return result;
}
/* $ANTLR end argument */

/** 
 * $ANTLR start named_expression
 * hammer_sema.gt:46:1: named_expression returns [const hammer::ast::expression* result] : ^( NamedArgument Id expression ) ;
 */
static const hammer::ast::expression*
named_expression(phammer_sema ctx)
{   
    const hammer::ast::expression* result = NULL;

    pANTLR3_BASE_TREE    Id6;
    const hammer::ast::expression* expression7;
    #undef	RETURN_TYPE_expression7
    #define	RETURN_TYPE_expression7 const hammer::ast::expression*

    /* Initialize rule variables
     */


    Id6       = NULL;
    expression7 = NULL;

    {
        // hammer_sema.gt:47:2: ( ^( NamedArgument Id expression ) )
        // hammer_sema.gt:47:4: ^( NamedArgument Id expression )
        {
             MATCHT(NamedArgument, &FOLLOW_NamedArgument_in_named_expression223); 
            if  (HASEXCEPTION())
            {
                goto rulenamed_expressionEx;
            }


            MATCHT(ANTLR3_TOKEN_DOWN, NULL); 
            if  (HASEXCEPTION())
            {
                goto rulenamed_expressionEx;
            }

            Id6 = (pANTLR3_BASE_TREE) MATCHT(Id, &FOLLOW_Id_in_named_expression225); 
            if  (HASEXCEPTION())
            {
                goto rulenamed_expressionEx;
            }

            FOLLOWPUSH(FOLLOW_expression_in_named_expression227);
            expression7=expression(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulenamed_expressionEx;
            }

            {
                 result = SEMA->on_named_expr(Id6->getToken(Id6), expression7); 
            }

            MATCHT(ANTLR3_TOKEN_UP, NULL); 
            if  (HASEXCEPTION())
            {
                goto rulenamed_expressionEx;
            }


        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulenamed_expressionEx; /* Prevent compiler warnings */
    rulenamed_expressionEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return result;
}
/* $ANTLR end named_expression */

/** 
 * $ANTLR start expression
 * hammer_sema.gt:50:1: expression returns [const hammer::ast::expression* result] : ( list_of[&args] | rule_invocation | feature | ^( PublicTag feature ) | target_def_or_rule_call | path | Id );
 */
static const hammer::ast::expression*
expression(phammer_sema ctx)
{   
    const hammer::ast::expression* result = NULL;

    pANTLR3_BASE_TREE    PublicTag10;
    pANTLR3_BASE_TREE    Id14;
    const hammer::ast::expression* rule_invocation8;
    #undef	RETURN_TYPE_rule_invocation8
    #define	RETURN_TYPE_rule_invocation8 const hammer::ast::expression*

    const hammer::ast::expression* feature9;
    #undef	RETURN_TYPE_feature9
    #define	RETURN_TYPE_feature9 const hammer::ast::expression*

    const hammer::ast::expression* feature11;
    #undef	RETURN_TYPE_feature11
    #define	RETURN_TYPE_feature11 const hammer::ast::expression*

    const hammer::ast::expression* target_def_or_rule_call12;
    #undef	RETURN_TYPE_target_def_or_rule_call12
    #define	RETURN_TYPE_target_def_or_rule_call12 const hammer::ast::expression*

    const hammer::ast::expression* path13;
    #undef	RETURN_TYPE_path13
    #define	RETURN_TYPE_path13 const hammer::ast::expression*

    /* Initialize rule variables
     */


     DECLARE_TYPE(hammer::ast::expressions_t, args); 
    PublicTag10       = NULL;
    Id14       = NULL;
    rule_invocation8 = NULL;
    feature9 = NULL;
    feature11 = NULL;
    target_def_or_rule_call12 = NULL;
    path13 = NULL;

    {
        {
            //  hammer_sema.gt:52:2: ( list_of[&args] | rule_invocation | feature | ^( PublicTag feature ) | target_def_or_rule_call | path | Id )
            
            ANTLR3_UINT32 alt4;

            alt4=7;

            switch ( LA(1) ) 
            {
            case List:
            	{
            		alt4=1;
            	}
                break;
            case RuleInvocation:
            	{
            		alt4=2;
            	}
                break;
            case Feature:
            	{
            		alt4=3;
            	}
                break;
            case PublicTag:
            	{
            		alt4=4;
            	}
                break;
            case Rule:
            	{
            		alt4=5;
            	}
                break;
            case Path:
            	{
            		alt4=6;
            	}
                break;
            case Id:
            	{
            		alt4=7;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 4;
                EXCEPTION->state        = 0;


                goto ruleexpressionEx;
            }

            switch (alt4) 
            {
        	case 1:
        	    // hammer_sema.gt:52:4: list_of[&args]
        	    {
        	        FOLLOWPUSH(FOLLOW_list_of_in_expression252);
        	        list_of(ctx, &args);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexpressionEx;
        	        }

        	        {
        	             result = SEMA->on_list_of(args); 
        	        }

        	    }
        	    break;
        	case 2:
        	    // hammer_sema.gt:56:4: rule_invocation
        	    {
        	        FOLLOWPUSH(FOLLOW_rule_invocation_in_expression263);
        	        rule_invocation8=rule_invocation(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexpressionEx;
        	        }

        	        {
        	             result = rule_invocation8; 
        	        }

        	    }
        	    break;
        	case 3:
        	    // hammer_sema.gt:57:4: feature
        	    {
        	        FOLLOWPUSH(FOLLOW_feature_in_expression270);
        	        feature9=feature(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexpressionEx;
        	        }

        	        {
        	             result = feature9; 
        	        }

        	    }
        	    break;
        	case 4:
        	    // hammer_sema.gt:58:4: ^( PublicTag feature )
        	    {
        	        PublicTag10 = (pANTLR3_BASE_TREE) MATCHT(PublicTag, &FOLLOW_PublicTag_in_expression278); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexpressionEx;
        	        }


        	        MATCHT(ANTLR3_TOKEN_DOWN, NULL); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexpressionEx;
        	        }

        	        FOLLOWPUSH(FOLLOW_feature_in_expression280);
        	        feature11=feature(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexpressionEx;
        	        }


        	        MATCHT(ANTLR3_TOKEN_UP, NULL); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexpressionEx;
        	        }

        	        {
        	             result = SEMA->on_public_expr(PublicTag10->getToken(PublicTag10), feature11); 
        	        }

        	    }
        	    break;
        	case 5:
        	    // hammer_sema.gt:59:4: target_def_or_rule_call
        	    {
        	        FOLLOWPUSH(FOLLOW_target_def_or_rule_call_in_expression288);
        	        target_def_or_rule_call12=target_def_or_rule_call(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexpressionEx;
        	        }

        	        {
        	             result = target_def_or_rule_call12; 
        	        }

        	    }
        	    break;
        	case 6:
        	    // hammer_sema.gt:60:4: path
        	    {
        	        FOLLOWPUSH(FOLLOW_path_in_expression295);
        	        path13=path(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexpressionEx;
        	        }

        	        {
        	             result = path13; 
        	        }

        	    }
        	    break;
        	case 7:
        	    // hammer_sema.gt:61:4: Id
        	    {
        	        Id14 = (pANTLR3_BASE_TREE) MATCHT(Id, &FOLLOW_Id_in_expression302); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexpressionEx;
        	        }

        	        {
        	             result = SEMA->on_id(Id14->getToken(Id14)); 
        	        }

        	    }
        	    break;

            }
        }
    }
    

    // This is where rules clean up and exit
    //
    goto ruleexpressionEx; /* Prevent compiler warnings */
    ruleexpressionEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return result;
}
/* $ANTLR end expression */

/** 
 * $ANTLR start expression_a
 * hammer_sema.gt:67:1: expression_a returns [const hammer::ast::expression* result] : ;
 */
static const hammer::ast::expression*
expression_a(phammer_sema ctx)
{   
    const hammer::ast::expression* result = NULL;

    /* Initialize rule variables
     */


    {
        // hammer_sema.gt:70:1: ()
        // hammer_sema.gt:70:3: 
        {
        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleexpression_aEx; /* Prevent compiler warnings */
    ruleexpression_aEx: ;


    return result;
}
/* $ANTLR end expression_a */

/** 
 * $ANTLR start list_of
 * hammer_sema.gt:72:1: list_of[hammer::ast::expressions_t* args] : ^( List ( list_element )+ ) ;
 */
static void
list_of(phammer_sema ctx, hammer::ast::expressions_t* args)
{   
    const hammer::ast::expression* list_element15;
    #undef	RETURN_TYPE_list_element15
    #define	RETURN_TYPE_list_element15 const hammer::ast::expression*

    /* Initialize rule variables
     */


    list_element15 = NULL;

    {
        // hammer_sema.gt:73:2: ( ^( List ( list_element )+ ) )
        // hammer_sema.gt:73:4: ^( List ( list_element )+ )
        {
             MATCHT(List, &FOLLOW_List_in_list_of334); 
            if  (HASEXCEPTION())
            {
                goto rulelist_ofEx;
            }


            MATCHT(ANTLR3_TOKEN_DOWN, NULL); 
            if  (HASEXCEPTION())
            {
                goto rulelist_ofEx;
            }

            // hammer_sema.gt:73:11: ( list_element )+
            {
                int cnt5=0;

                for (;;)
                {
                    int alt5=2;
            	{
            	   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
            	    */
            	    int LA5_0 = LA(1);
            	    if ( (LA5_0 == Feature || ((LA5_0 >= RuleInvocation) && (LA5_0 <= Path)) || LA5_0 == Id || LA5_0 == PublicTag) ) 
            	    {
            	        alt5=1;
            	    }

            	}
            	switch (alt5) 
            	{
            	    case 1:
            	        // hammer_sema.gt:73:12: list_element
            	        {
            	            FOLLOWPUSH(FOLLOW_list_element_in_list_of337);
            	            list_element15=list_element(ctx);

            	            FOLLOWPOP();
            	            if  (HASEXCEPTION())
            	            {
            	                goto rulelist_ofEx;
            	            }

            	            {
            	                 args->push_back(list_element15); 
            	            }

            	        }
            	        break;

            	    default:
            	    
            		if ( cnt5 >= 1 )
            		{
            		    goto loop5;
            		}
            		/* mismatchedSetEx()
            		 */
            		CONSTRUCTEX();
            		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
            		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


            		goto rulelist_ofEx;
            	}
            	cnt5++;
                }
                loop5: ;	/* Jump to here if this rule does not match */
            }

            MATCHT(ANTLR3_TOKEN_UP, NULL); 
            if  (HASEXCEPTION())
            {
                goto rulelist_ofEx;
            }


        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulelist_ofEx; /* Prevent compiler warnings */
    rulelist_ofEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return ;
}
/* $ANTLR end list_of */

/** 
 * $ANTLR start list_element
 * hammer_sema.gt:75:1: list_element returns [const hammer::ast::expression* result] : ( rule_invocation | path | feature | ^( PublicTag feature ) | Id );
 */
static const hammer::ast::expression*
list_element(phammer_sema ctx)
{   
    const hammer::ast::expression* result = NULL;

    pANTLR3_BASE_TREE    PublicTag19;
    pANTLR3_BASE_TREE    Id21;
    const hammer::ast::expression* rule_invocation16;
    #undef	RETURN_TYPE_rule_invocation16
    #define	RETURN_TYPE_rule_invocation16 const hammer::ast::expression*

    const hammer::ast::expression* path17;
    #undef	RETURN_TYPE_path17
    #define	RETURN_TYPE_path17 const hammer::ast::expression*

    const hammer::ast::expression* feature18;
    #undef	RETURN_TYPE_feature18
    #define	RETURN_TYPE_feature18 const hammer::ast::expression*

    const hammer::ast::expression* feature20;
    #undef	RETURN_TYPE_feature20
    #define	RETURN_TYPE_feature20 const hammer::ast::expression*

    /* Initialize rule variables
     */


    PublicTag19       = NULL;
    Id21       = NULL;
    rule_invocation16 = NULL;
    path17 = NULL;
    feature18 = NULL;
    feature20 = NULL;

    {
        {
            //  hammer_sema.gt:76:2: ( rule_invocation | path | feature | ^( PublicTag feature ) | Id )
            
            ANTLR3_UINT32 alt6;

            alt6=5;

            switch ( LA(1) ) 
            {
            case RuleInvocation:
            	{
            		alt6=1;
            	}
                break;
            case Path:
            	{
            		alt6=2;
            	}
                break;
            case Feature:
            	{
            		alt6=3;
            	}
                break;
            case PublicTag:
            	{
            		alt6=4;
            	}
                break;
            case Id:
            	{
            		alt6=5;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 6;
                EXCEPTION->state        = 0;


                goto rulelist_elementEx;
            }

            switch (alt6) 
            {
        	case 1:
        	    // hammer_sema.gt:79:4: rule_invocation
        	    {
        	        FOLLOWPUSH(FOLLOW_rule_invocation_in_list_element373);
        	        rule_invocation16=rule_invocation(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulelist_elementEx;
        	        }

        	        {
        	             result = rule_invocation16; 
        	        }

        	    }
        	    break;
        	case 2:
        	    // hammer_sema.gt:80:4: path
        	    {
        	        FOLLOWPUSH(FOLLOW_path_in_list_element380);
        	        path17=path(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulelist_elementEx;
        	        }

        	        {
        	             result = path17; 
        	        }

        	    }
        	    break;
        	case 3:
        	    // hammer_sema.gt:81:4: feature
        	    {
        	        FOLLOWPUSH(FOLLOW_feature_in_list_element387);
        	        feature18=feature(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulelist_elementEx;
        	        }

        	        {
        	             result = feature18; 
        	        }

        	    }
        	    break;
        	case 4:
        	    // hammer_sema.gt:82:4: ^( PublicTag feature )
        	    {
        	        PublicTag19 = (pANTLR3_BASE_TREE) MATCHT(PublicTag, &FOLLOW_PublicTag_in_list_element395); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulelist_elementEx;
        	        }


        	        MATCHT(ANTLR3_TOKEN_DOWN, NULL); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulelist_elementEx;
        	        }

        	        FOLLOWPUSH(FOLLOW_feature_in_list_element397);
        	        feature20=feature(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulelist_elementEx;
        	        }


        	        MATCHT(ANTLR3_TOKEN_UP, NULL); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulelist_elementEx;
        	        }

        	        {
        	             result = SEMA->on_public_expr(PublicTag19->getToken(PublicTag19), feature20); 
        	        }

        	    }
        	    break;
        	case 5:
        	    // hammer_sema.gt:83:4: Id
        	    {
        	        Id21 = (pANTLR3_BASE_TREE) MATCHT(Id, &FOLLOW_Id_in_list_element405); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulelist_elementEx;
        	        }

        	        {
        	             result = SEMA->on_id(Id21->getToken(Id21)); 
        	        }

        	    }
        	    break;

            }
        }
    }
    

    // This is where rules clean up and exit
    //
    goto rulelist_elementEx; /* Prevent compiler warnings */
    rulelist_elementEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return result;
}
/* $ANTLR end list_element */

/** 
 * $ANTLR start path
 * hammer_sema.gt:86:1: path returns [const hammer::ast::expression* result] : ^( Path path_impl[&bounds] ) ;
 */
static const hammer::ast::expression*
path(phammer_sema ctx)
{   
    const hammer::ast::expression* result = NULL;

    /* Initialize rule variables
     */


     std::pair<pANTLR3_COMMON_TOKEN, pANTLR3_COMMON_TOKEN> bounds; 
    {
        // hammer_sema.gt:88:2: ( ^( Path path_impl[&bounds] ) )
        // hammer_sema.gt:88:4: ^( Path path_impl[&bounds] )
        {
             MATCHT(Path, &FOLLOW_Path_in_path427); 
            if  (HASEXCEPTION())
            {
                goto rulepathEx;
            }


            MATCHT(ANTLR3_TOKEN_DOWN, NULL); 
            if  (HASEXCEPTION())
            {
                goto rulepathEx;
            }

            FOLLOWPUSH(FOLLOW_path_impl_in_path429);
            path_impl(ctx, &bounds);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulepathEx;
            }


            MATCHT(ANTLR3_TOKEN_UP, NULL); 
            if  (HASEXCEPTION())
            {
                goto rulepathEx;
            }

            {
                 result = SEMA->on_path_like_seq(bounds.first, bounds.second); 
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulepathEx; /* Prevent compiler warnings */
    rulepathEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return result;
}
/* $ANTLR end path */

/** 
 * $ANTLR start path_impl
 * hammer_sema.gt:91:1: path_impl[std::pair<pANTLR3_COMMON_TOKEN, pANTLR3_COMMON_TOKEN>* bounds] : ( Slash ( path_element )+ last= path_element | first= path_element ( path_element )* last= path_element );
 */
static void
path_impl(phammer_sema ctx, std::pair<pANTLR3_COMMON_TOKEN, pANTLR3_COMMON_TOKEN>* bounds)
{   
    pANTLR3_BASE_TREE    Slash22;
    pANTLR3_COMMON_TOKEN last;
    #undef	RETURN_TYPE_last
    #define	RETURN_TYPE_last pANTLR3_COMMON_TOKEN

    pANTLR3_COMMON_TOKEN first;
    #undef	RETURN_TYPE_first
    #define	RETURN_TYPE_first pANTLR3_COMMON_TOKEN

    /* Initialize rule variables
     */


    Slash22       = NULL;
    last = NULL;
    first = NULL;

    {
        {
            //  hammer_sema.gt:92:2: ( Slash ( path_element )+ last= path_element | first= path_element ( path_element )* last= path_element )
            
            ANTLR3_UINT32 alt9;

            alt9=2;


            {
                int LA9_0 = LA(1);
                if ( (LA9_0 == Slash) ) 
                {
                    alt9=1;
                }
                else if ( (LA9_0 == Wildcard || LA9_0 == Id) ) 
                {
                    alt9=2;
                }
                else 
                {
                
                    CONSTRUCTEX();
                    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                    EXCEPTION->message      = (void *)"";
                    EXCEPTION->decisionNum  = 9;
                    EXCEPTION->state        = 0;


                    goto rulepath_implEx;
                }
            }
            switch (alt9) 
            {
        	case 1:
        	    // hammer_sema.gt:92:4: Slash ( path_element )+ last= path_element
        	    {
        	        Slash22 = (pANTLR3_BASE_TREE) MATCHT(Slash, &FOLLOW_Slash_in_path_impl446); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulepath_implEx;
        	        }

        	        // hammer_sema.gt:92:10: ( path_element )+
        	        {
        	            int cnt7=0;

        	            for (;;)
        	            {
        	                int alt7=2;
        	        	alt7 = cdfa7.predict(ctx, RECOGNIZER, ISTREAM, &cdfa7);
        	        	if  (HASEXCEPTION())
        	        	{
        	        	    goto rulepath_implEx;
        	        	}

        	        	switch (alt7) 
        	        	{
        	        	    case 1:
        	        	        // hammer_sema.gt:92:10: path_element
        	        	        {
        	        	            FOLLOWPUSH(FOLLOW_path_element_in_path_impl448);
        	        	            path_element(ctx);

        	        	            FOLLOWPOP();
        	        	            if  (HASEXCEPTION())
        	        	            {
        	        	                goto rulepath_implEx;
        	        	            }


        	        	        }
        	        	        break;

        	        	    default:
        	        	    
        	        		if ( cnt7 >= 1 )
        	        		{
        	        		    goto loop7;
        	        		}
        	        		/* mismatchedSetEx()
        	        		 */
        	        		CONSTRUCTEX();
        	        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        	        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        	        		goto rulepath_implEx;
        	        	}
        	        	cnt7++;
        	            }
        	            loop7: ;	/* Jump to here if this rule does not match */
        	        }
        	        FOLLOWPUSH(FOLLOW_path_element_in_path_impl453);
        	        last=path_element(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulepath_implEx;
        	        }

        	        {
        	             bounds->first = Slash22->getToken(Slash22); bounds->second = last; 
        	        }

        	    }
        	    break;
        	case 2:
        	    // hammer_sema.gt:93:4: first= path_element ( path_element )* last= path_element
        	    {
        	        FOLLOWPUSH(FOLLOW_path_element_in_path_impl462);
        	        first=path_element(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulepath_implEx;
        	        }


        	        // hammer_sema.gt:93:23: ( path_element )*

        	        for (;;)
        	        {
        	            int alt8=2;
        	            alt8 = cdfa8.predict(ctx, RECOGNIZER, ISTREAM, &cdfa8);
        	            if  (HASEXCEPTION())
        	            {
        	                goto rulepath_implEx;
        	            }

        	            switch (alt8) 
        	            {
        	        	case 1:
        	        	    // hammer_sema.gt:93:23: path_element
        	        	    {
        	        	        FOLLOWPUSH(FOLLOW_path_element_in_path_impl464);
        	        	        path_element(ctx);

        	        	        FOLLOWPOP();
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto rulepath_implEx;
        	        	        }


        	        	    }
        	        	    break;

        	        	default:
        	        	    goto loop8;	/* break out of the loop */
        	        	    break;
        	            }
        	        }
        	        loop8: ; /* Jump out to here if this rule does not match */

        	        FOLLOWPUSH(FOLLOW_path_element_in_path_impl469);
        	        last=path_element(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulepath_implEx;
        	        }

        	        {
        	             bounds->first = first; bounds->second = last; 
        	        }

        	    }
        	    break;

            }
        }
    }
    

    // This is where rules clean up and exit
    //
    goto rulepath_implEx; /* Prevent compiler warnings */
    rulepath_implEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return ;
}
/* $ANTLR end path_impl */

/** 
 * $ANTLR start path_element
 * hammer_sema.gt:96:1: path_element returns [pANTLR3_COMMON_TOKEN result] : ( Id | wildcard );
 */
static pANTLR3_COMMON_TOKEN
path_element(phammer_sema ctx)
{   
    pANTLR3_COMMON_TOKEN result = NULL;

    pANTLR3_BASE_TREE    Id23;
    pANTLR3_COMMON_TOKEN wildcard24;
    #undef	RETURN_TYPE_wildcard24
    #define	RETURN_TYPE_wildcard24 pANTLR3_COMMON_TOKEN

    /* Initialize rule variables
     */


    Id23       = NULL;
    wildcard24 = NULL;

    {
        {
            //  hammer_sema.gt:97:2: ( Id | wildcard )
            
            ANTLR3_UINT32 alt10;

            alt10=2;


            {
                int LA10_0 = LA(1);
                if ( (LA10_0 == Id) ) 
                {
                    alt10=1;
                }
                else if ( (LA10_0 == Wildcard) ) 
                {
                    alt10=2;
                }
                else 
                {
                
                    CONSTRUCTEX();
                    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                    EXCEPTION->message      = (void *)"";
                    EXCEPTION->decisionNum  = 10;
                    EXCEPTION->state        = 0;


                    goto rulepath_elementEx;
                }
            }
            switch (alt10) 
            {
        	case 1:
        	    // hammer_sema.gt:97:4: Id
        	    {
        	        Id23 = (pANTLR3_BASE_TREE) MATCHT(Id, &FOLLOW_Id_in_path_element485); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulepath_elementEx;
        	        }

        	        {
        	             result = Id23->getToken(Id23); 
        	        }

        	    }
        	    break;
        	case 2:
        	    // hammer_sema.gt:98:4: wildcard
        	    {
        	        FOLLOWPUSH(FOLLOW_wildcard_in_path_element492);
        	        wildcard24=wildcard(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulepath_elementEx;
        	        }

        	        {
        	             result = wildcard24; 
        	        }

        	    }
        	    break;

            }
        }
    }
    

    // This is where rules clean up and exit
    //
    goto rulepath_elementEx; /* Prevent compiler warnings */
    rulepath_elementEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return result;
}
/* $ANTLR end path_element */

/** 
 * $ANTLR start wildcard
 * hammer_sema.gt:101:1: wildcard returns [pANTLR3_COMMON_TOKEN result] : ^( Wildcard ( wildcard_elem )* last= wildcard_elem ) ;
 */
static pANTLR3_COMMON_TOKEN
wildcard(phammer_sema ctx)
{   
    pANTLR3_COMMON_TOKEN result = NULL;

    pANTLR3_COMMON_TOKEN last;
    #undef	RETURN_TYPE_last
    #define	RETURN_TYPE_last pANTLR3_COMMON_TOKEN

    /* Initialize rule variables
     */


    last = NULL;

    {
        // hammer_sema.gt:102:2: ( ^( Wildcard ( wildcard_elem )* last= wildcard_elem ) )
        // hammer_sema.gt:102:4: ^( Wildcard ( wildcard_elem )* last= wildcard_elem )
        {
             MATCHT(Wildcard, &FOLLOW_Wildcard_in_wildcard509); 
            if  (HASEXCEPTION())
            {
                goto rulewildcardEx;
            }


            MATCHT(ANTLR3_TOKEN_DOWN, NULL); 
            if  (HASEXCEPTION())
            {
                goto rulewildcardEx;
            }


            // hammer_sema.gt:102:15: ( wildcard_elem )*

            for (;;)
            {
                int alt11=2;
                switch ( LA(1) ) 
                {
                case Id:
                	{
                		{
                		   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                		    */
                		    int LA11_1 = LA(2);
                		    if ( (LA11_1 == Id || ((LA11_1 >= QuestionMark) && (LA11_1 <= Asterix))) ) 
                		    {
                		        alt11=1;
                		    }

                		}
                	}
                    break;
                case QuestionMark:
                	{
                		{
                		   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                		    */
                		    int LA11_2 = LA(2);
                		    if ( (LA11_2 == Id || ((LA11_2 >= QuestionMark) && (LA11_2 <= Asterix))) ) 
                		    {
                		        alt11=1;
                		    }

                		}
                	}
                    break;
                case Asterix:
                	{
                		{
                		   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                		    */
                		    int LA11_3 = LA(2);
                		    if ( (LA11_3 == Id || ((LA11_3 >= QuestionMark) && (LA11_3 <= Asterix))) ) 
                		    {
                		        alt11=1;
                		    }

                		}
                	}
                    break;

                }

                switch (alt11) 
                {
            	case 1:
            	    // hammer_sema.gt:102:15: wildcard_elem
            	    {
            	        FOLLOWPUSH(FOLLOW_wildcard_elem_in_wildcard511);
            	        wildcard_elem(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulewildcardEx;
            	        }


            	    }
            	    break;

            	default:
            	    goto loop11;	/* break out of the loop */
            	    break;
                }
            }
            loop11: ; /* Jump out to here if this rule does not match */

            FOLLOWPUSH(FOLLOW_wildcard_elem_in_wildcard516);
            last=wildcard_elem(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulewildcardEx;
            }

            {
                 result = last; 
            }

            MATCHT(ANTLR3_TOKEN_UP, NULL); 
            if  (HASEXCEPTION())
            {
                goto rulewildcardEx;
            }


        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulewildcardEx; /* Prevent compiler warnings */
    rulewildcardEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return result;
}
/* $ANTLR end wildcard */

/** 
 * $ANTLR start wildcard_elem
 * hammer_sema.gt:105:1: wildcard_elem returns [pANTLR3_COMMON_TOKEN result] : ( Id | QuestionMark | Asterix );
 */
static pANTLR3_COMMON_TOKEN
wildcard_elem(phammer_sema ctx)
{   
    pANTLR3_COMMON_TOKEN result = NULL;

    pANTLR3_BASE_TREE    Id25;
    pANTLR3_BASE_TREE    QuestionMark26;
    pANTLR3_BASE_TREE    Asterix27;

    /* Initialize rule variables
     */


    Id25       = NULL;
    QuestionMark26       = NULL;
    Asterix27       = NULL;

    {
        {
            //  hammer_sema.gt:106:2: ( Id | QuestionMark | Asterix )
            
            ANTLR3_UINT32 alt12;

            alt12=3;

            switch ( LA(1) ) 
            {
            case Id:
            	{
            		alt12=1;
            	}
                break;
            case QuestionMark:
            	{
            		alt12=2;
            	}
                break;
            case Asterix:
            	{
            		alt12=3;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 12;
                EXCEPTION->state        = 0;


                goto rulewildcard_elemEx;
            }

            switch (alt12) 
            {
        	case 1:
        	    // hammer_sema.gt:106:4: Id
        	    {
        	        Id25 = (pANTLR3_BASE_TREE) MATCHT(Id, &FOLLOW_Id_in_wildcard_elem534); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulewildcard_elemEx;
        	        }

        	        {
        	             result = Id25->getToken(Id25); 
        	        }

        	    }
        	    break;
        	case 2:
        	    // hammer_sema.gt:107:4: QuestionMark
        	    {
        	        QuestionMark26 = (pANTLR3_BASE_TREE) MATCHT(QuestionMark, &FOLLOW_QuestionMark_in_wildcard_elem541); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulewildcard_elemEx;
        	        }

        	        {
        	             result = QuestionMark26->getToken(QuestionMark26); 
        	        }

        	    }
        	    break;
        	case 3:
        	    // hammer_sema.gt:108:4: Asterix
        	    {
        	        Asterix27 = (pANTLR3_BASE_TREE) MATCHT(Asterix, &FOLLOW_Asterix_in_wildcard_elem548); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulewildcard_elemEx;
        	        }

        	        {
        	             result = Asterix27->getToken(Asterix27); 
        	        }

        	    }
        	    break;

            }
        }
    }
    

    // This is where rules clean up and exit
    //
    goto rulewildcard_elemEx; /* Prevent compiler warnings */
    rulewildcard_elemEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return result;
}
/* $ANTLR end wildcard_elem */

/** 
 * $ANTLR start public_tag
 * hammer_sema.gt:111:1: public_tag[hammer::parscore::source_location* tag_loc] : Public ;
 */
static void
public_tag(phammer_sema ctx, hammer::parscore::source_location* tag_loc)
{   
    pANTLR3_BASE_TREE    Public28;

    /* Initialize rule variables
     */


    Public28       = NULL;

    {
        // hammer_sema.gt:112:2: ( Public )
        // hammer_sema.gt:112:4: Public
        {
            Public28 = (pANTLR3_BASE_TREE) MATCHT(Public, &FOLLOW_Public_in_public_tag563); 
            if  (HASEXCEPTION())
            {
                goto rulepublic_tagEx;
            }

            {
                 *tag_loc = hammer::parscore::source_location(Public28->getToken(Public28)); 
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulepublic_tagEx; /* Prevent compiler warnings */
    rulepublic_tagEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return ;
}
/* $ANTLR end public_tag */

/** 
 * $ANTLR start rule_invocation
 * hammer_sema.gt:115:1: rule_invocation returns [const hammer::ast::expression* result] : ^( RuleInvocation name= Id arguments[&args] ) ;
 */
static const hammer::ast::expression*
rule_invocation(phammer_sema ctx)
{   
    const hammer::ast::expression* result = NULL;

    pANTLR3_BASE_TREE    name;

    /* Initialize rule variables
     */


     DECLARE_TYPE(hammer::ast::expressions_t, args); 
    name       = NULL;

    {
        // hammer_sema.gt:117:2: ( ^( RuleInvocation name= Id arguments[&args] ) )
        // hammer_sema.gt:117:4: ^( RuleInvocation name= Id arguments[&args] )
        {
             MATCHT(RuleInvocation, &FOLLOW_RuleInvocation_in_rule_invocation586); 
            if  (HASEXCEPTION())
            {
                goto rulerule_invocationEx;
            }


            MATCHT(ANTLR3_TOKEN_DOWN, NULL); 
            if  (HASEXCEPTION())
            {
                goto rulerule_invocationEx;
            }

            name = (pANTLR3_BASE_TREE) MATCHT(Id, &FOLLOW_Id_in_rule_invocation590); 
            if  (HASEXCEPTION())
            {
                goto rulerule_invocationEx;
            }

            FOLLOWPUSH(FOLLOW_arguments_in_rule_invocation592);
            arguments(ctx, &args);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulerule_invocationEx;
            }


            MATCHT(ANTLR3_TOKEN_UP, NULL); 
            if  (HASEXCEPTION())
            {
                goto rulerule_invocationEx;
            }

            {
                 result = SEMA->on_target_or_rule_call(name->getToken(name), args); 
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulerule_invocationEx; /* Prevent compiler warnings */
    rulerule_invocationEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return result;
}
/* $ANTLR end rule_invocation */

/** 
 * $ANTLR start feature
 * hammer_sema.gt:120:1: feature returns [const hammer::ast::expression* result] : ^( Feature Id feature_value ) ;
 */
static const hammer::ast::expression*
feature(phammer_sema ctx)
{   
    const hammer::ast::expression* result = NULL;

    pANTLR3_BASE_TREE    Id29;
    const hammer::ast::expression* feature_value30;
    #undef	RETURN_TYPE_feature_value30
    #define	RETURN_TYPE_feature_value30 const hammer::ast::expression*

    /* Initialize rule variables
     */


    Id29       = NULL;
    feature_value30 = NULL;

    {
        // hammer_sema.gt:121:2: ( ^( Feature Id feature_value ) )
        // hammer_sema.gt:121:4: ^( Feature Id feature_value )
        {
             MATCHT(Feature, &FOLLOW_Feature_in_feature611); 
            if  (HASEXCEPTION())
            {
                goto rulefeatureEx;
            }


            MATCHT(ANTLR3_TOKEN_DOWN, NULL); 
            if  (HASEXCEPTION())
            {
                goto rulefeatureEx;
            }

            Id29 = (pANTLR3_BASE_TREE) MATCHT(Id, &FOLLOW_Id_in_feature613); 
            if  (HASEXCEPTION())
            {
                goto rulefeatureEx;
            }

            FOLLOWPUSH(FOLLOW_feature_value_in_feature615);
            feature_value30=feature_value(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulefeatureEx;
            }


            MATCHT(ANTLR3_TOKEN_UP, NULL); 
            if  (HASEXCEPTION())
            {
                goto rulefeatureEx;
            }

            {
                 result = SEMA->on_feature(Id29->getToken(Id29), feature_value30); 
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulefeatureEx; /* Prevent compiler warnings */
    rulefeatureEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return result;
}
/* $ANTLR end feature */

/** 
 * $ANTLR start feature_value
 * hammer_sema.gt:124:1: feature_value returns [const hammer::ast::expression* result] : ( Id | path );
 */
static const hammer::ast::expression*
feature_value(phammer_sema ctx)
{   
    const hammer::ast::expression* result = NULL;

    pANTLR3_BASE_TREE    Id31;
    const hammer::ast::expression* path32;
    #undef	RETURN_TYPE_path32
    #define	RETURN_TYPE_path32 const hammer::ast::expression*

    /* Initialize rule variables
     */


    Id31       = NULL;
    path32 = NULL;

    {
        {
            //  hammer_sema.gt:125:2: ( Id | path )
            
            ANTLR3_UINT32 alt13;

            alt13=2;


            {
                int LA13_0 = LA(1);
                if ( (LA13_0 == Id) ) 
                {
                    alt13=1;
                }
                else if ( (LA13_0 == Path) ) 
                {
                    alt13=2;
                }
                else 
                {
                
                    CONSTRUCTEX();
                    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                    EXCEPTION->message      = (void *)"";
                    EXCEPTION->decisionNum  = 13;
                    EXCEPTION->state        = 0;


                    goto rulefeature_valueEx;
                }
            }
            switch (alt13) 
            {
        	case 1:
        	    // hammer_sema.gt:125:4: Id
        	    {
        	        Id31 = (pANTLR3_BASE_TREE) MATCHT(Id, &FOLLOW_Id_in_feature_value633); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulefeature_valueEx;
        	        }

        	        {
        	             result = SEMA->on_id(Id31->getToken(Id31)); 
        	        }

        	    }
        	    break;
        	case 2:
        	    // hammer_sema.gt:126:4: path
        	    {
        	        FOLLOWPUSH(FOLLOW_path_in_feature_value640);
        	        path32=path(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulefeature_valueEx;
        	        }

        	        {
        	             result = path32; 
        	        }

        	    }
        	    break;

            }
        }
    }
    

    // This is where rules clean up and exit
    //
    goto rulefeature_valueEx; /* Prevent compiler warnings */
    rulefeature_valueEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return result;
}
/* $ANTLR end feature_value */
/* End of parsing rules
 * ==============================================
 */

/* ==============================================
 * Syntactic predicates
 */
/* End of syntactic predicates
 * ==============================================
 */

 
 



/* End of code
 * =============================================================================
 */
