/** \file
 *  This C source file was generated by $ANTLR version 3.1.1
 *
 *     -  From the grammar source file : hammer_v2.g
 *     -                            On : 2018-12-15 19:32:29
 *     -                 for the lexer : hammer_v2LexerLexer *
 * Editing it, at least manually, is not wise. 
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "hammer_v2Lexer.h"
/* ----------------------------------------- */


/** String literals used by hammer_v2Lexer that we must do things like MATCHS() with.
 *  C will normally just lay down 8 bit characters, and you can use L"xxx" to
 *  get wchar_t, but wchar_t is 16 bits on Windows, which is not UTF32 and so
 *  we perform this little trick of defining the literals as arrays of UINT32
 *  and passing in the address of these.
 */
static ANTLR3_UCHAR	lit_1[]  = { 0x2D, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_2[]  = { 0x7C, 0x7C,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_3[]  = { 0x26, 0x26,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_4[]  = { 0x66, 0x69, 0x6C, 0x65, 0x3A, 0x2F, 0x2F,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_5[]  = { 0x2F, 0x2F,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_6[]  = { 0x6C, 0x6F, 0x63, 0x61, 0x6C,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_7[]  = { 0x65, 0x78, 0x70, 0x6C, 0x69, 0x63, 0x69, 0x74,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_8[]  = { 0x2A, 0x2A,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_9[]  = { 0x5C, 0x22,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_10[]  = { 0x5C, 0x27,  ANTLR3_STRING_TERMINATOR};




/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */
 
#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   phammer_v2Lexer_##scope##_SCOPE
#define SCOPE_STACK(scope)  phammer_v2Lexer_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->phammer_v2Lexer_##scope##Top
#define	SCOPE_SIZE(scope)			(ctx->SCOPE_STACK(scope)->size(ctx->SCOPE_STACK(scope)))
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

 
/* Macros for accessing things in a lexer
 */
#undef	    LEXER
#undef	    RECOGNIZER		    
#undef	    RULEMEMO		    
#undef	    GETCHARINDEX
#undef	    GETLINE
#undef	    GETCHARPOSITIONINLINE
#undef	    EMIT
#undef	    EMITNEW
#undef	    MATCHC
#undef	    MATCHS
#undef	    MATCHRANGE
#undef	    LTOKEN
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    INPUT
#undef	    STRSTREAM
#undef	    LA
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    LRECOVER
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    BACKTRACKING
#undef		MATCHANY
#undef		MEMOIZE
#undef		HAVEPARSEDRULE
#undef		GETTEXT
#undef		INDEX
#undef		SEEK
#undef		PUSHSTREAM
#undef		POPSTREAM
#undef		SETTEXT
#undef		SETTEXT8

#define	    LEXER					ctx->pLexer
#define	    RECOGNIZER			    LEXER->rec
#define		LEXSTATE				RECOGNIZER->state
#define		TOKSOURCE				LEXSTATE->tokSource
#define	    GETCHARINDEX()			LEXER->getCharIndex(LEXER)
#define	    GETLINE()				LEXER->getLine(LEXER)
#define	    GETTEXT()				LEXER->getText(LEXER)
#define	    GETCHARPOSITIONINLINE() LEXER->getCharPositionInLine(LEXER)
#define	    EMIT()					LEXSTATE->type = _type; LEXER->emit(LEXER)
#define	    EMITNEW(t)				LEXER->emitNew(LEXER, t)
#define	    MATCHC(c)				LEXER->matchc(LEXER, c)
#define	    MATCHS(s)				LEXER->matchs(LEXER, s)
#define	    MATCHRANGE(c1,c2)	    LEXER->matchRange(LEXER, c1, c2)
#define	    MATCHANY()				LEXER->matchAny(LEXER)
#define	    LTOKEN  				LEXSTATE->token
#define	    HASFAILED()				(LEXSTATE->failed == ANTLR3_TRUE)
#define	    BACKTRACKING			LEXSTATE->backtracking
#define	    FAILEDFLAG				LEXSTATE->failed
#define	    INPUT					LEXER->input
#define	    STRSTREAM				INPUT
#define		ISTREAM					INPUT->istream
#define		INDEX()					ISTREAM->index(ISTREAM)
#define		SEEK(n)					ISTREAM->seek(ISTREAM, n)
#define	    EOF_TOKEN				&(LEXSTATE->tokSource->eofToken)
#define	    HASEXCEPTION()			(LEXSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				LEXSTATE->exception
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    LRECOVER()				LEXER->recover(LEXER)
#define	    MARK()					ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define		MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define		HAVEPARSEDRULE(r)		RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define		PUSHSTREAM(str)			LEXER->pushCharStream(LEXER, str)
#define		POPSTREAM()				LEXER->popCharStream(LEXER)
#define		SETTEXT(str)			LEXSTATE->text = str
#define		SKIP()					LEXSTATE->token = &(TOKSOURCE->skipToken)
#define		USER1					LEXSTATE->user1
#define		USER2					LEXSTATE->user2
#define		USER3					LEXSTATE->user3
#define		CUSTOM					LEXSTATE->custom
#define		RULEMEMO				LEXSTATE->ruleMemo
#define		DBG						RECOGNIZER->debugger

/* If we have been told we can rely on the standard 8 bit or 16 bit input
 * stream, then we can define our macros to use the direct pointers
 * in the input object, which is much faster than indirect calls. This
 * is really only significant to lexers with a lot of fragment rules (which
 * do not place LA(1) in a temporary at the moment) and even then
 * only if there is a lot of input (order of say 1M or so).
 */
#if	defined(ANTLR3_INLINE_INPUT_ASCII) || defined(ANTLR3_INLINE_INPUT_UTF16)

# ifdef	ANTLR3_INLINE_INPUT_ASCII

/* 8 bit "ASCII" (actually any 8 bit character set) */

#  define	    NEXTCHAR			((pANTLR3_UINT8)(INPUT->nextChar))
#  define	    DATAP				((pANTLR3_UINT8)(INPUT->data))

# else

#  define	    NEXTCHAR			((pANTLR3_UINT16)(INPUT->nextChar)) 
#  define	    DATAP				((pANTLR3_UINT16)(INPUT->data))

# endif

# define	    LA(n) ((NEXTCHAR + n) > (DATAP + INPUT->sizeBuf) ? ANTLR3_CHARSTREAM_EOF : (ANTLR3_UCHAR)(*(NEXTCHAR + n - 1)))
# define	    CONSUME()											\
{																	\
    if	(NEXTCHAR < (DATAP + INPUT->sizeBuf))						\
    {																\
		INPUT->charPositionInLine++;								\
		if  ((ANTLR3_UCHAR)(*NEXTCHAR) == INPUT->newlineChar)		\
		{															\
			INPUT->line++;											\
			INPUT->charPositionInLine	= 0;						\
			INPUT->currentLine		= (void *)(NEXTCHAR + 1);		\
		}															\
		INPUT->nextChar = (void *)(NEXTCHAR + 1);					\
    }																\
}

#else

// Pick up the input character by calling the input stream implementation.
//
#define	    CONSUME()				INPUT->istream->consume(INPUT->istream)
#define	    LA(n)					INPUT->istream->_LA(INPUT->istream, n)

#endif
#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */


/* Forward declare the locally static matching functions we have generated and any predicate functions.
 */
static ANTLR3_INLINE  void	mT__41    (phammer_v2Lexer ctx);
static ANTLR3_INLINE  void	mT__42    (phammer_v2Lexer ctx);
static ANTLR3_INLINE  void	mT__43    (phammer_v2Lexer ctx);
static ANTLR3_INLINE  void	mT__44    (phammer_v2Lexer ctx);
static ANTLR3_INLINE  void	mT__45    (phammer_v2Lexer ctx);
static ANTLR3_INLINE  void	mT__46    (phammer_v2Lexer ctx);
static ANTLR3_INLINE  void	mT__47    (phammer_v2Lexer ctx);
static ANTLR3_INLINE  void	mT__48    (phammer_v2Lexer ctx);
static ANTLR3_INLINE  void	mT__49    (phammer_v2Lexer ctx);
static ANTLR3_INLINE  void	mT__50    (phammer_v2Lexer ctx);
static ANTLR3_INLINE  void	mT__51    (phammer_v2Lexer ctx);
static ANTLR3_INLINE  void	mT__52    (phammer_v2Lexer ctx);
static ANTLR3_INLINE  void	mT__53    (phammer_v2Lexer ctx);
static ANTLR3_INLINE  void	mT__54    (phammer_v2Lexer ctx);
static ANTLR3_INLINE  void	mPathUri    (phammer_v2Lexer ctx);
static ANTLR3_INLINE  void	mSlash    (phammer_v2Lexer ctx);
static ANTLR3_INLINE  void	mDoubleSlash    (phammer_v2Lexer ctx);
static ANTLR3_INLINE  void	mPublicTag    (phammer_v2Lexer ctx);
static ANTLR3_INLINE  void	mLocal    (phammer_v2Lexer ctx);
static ANTLR3_INLINE  void	mExplicit    (phammer_v2Lexer ctx);
static ANTLR3_INLINE  void	mQuestionMark    (phammer_v2Lexer ctx);
static ANTLR3_INLINE  void	mAsterix    (phammer_v2Lexer ctx);
static ANTLR3_INLINE  void	mDoubleAsterix    (phammer_v2Lexer ctx);
static ANTLR3_INLINE  void	mId    (phammer_v2Lexer ctx);
static ANTLR3_INLINE  void	mSTRING    (phammer_v2Lexer ctx);
static ANTLR3_INLINE  void	mSTRING_ID    (phammer_v2Lexer ctx);
static ANTLR3_INLINE  void	mSTRING_1    (phammer_v2Lexer ctx);
static ANTLR3_INLINE  void	mSTRING_ID1    (phammer_v2Lexer ctx);
static ANTLR3_INLINE  void	mCOMMENT    (phammer_v2Lexer ctx);
static ANTLR3_INLINE  void	mWS    (phammer_v2Lexer ctx);
static ANTLR3_INLINE  void	mTokens    (phammer_v2Lexer ctx);
static void	hammer_v2LexerFree(phammer_v2Lexer ctx);

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */



static void
hammer_v2LexerFree  (phammer_v2Lexer ctx)
{
    LEXER->free(LEXER);
    
    ANTLR3_FREE(ctx);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "hammer_v2.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}

/** \brief Create a new lexer called hammer_v2Lexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \return 
 *     - Success phammer_v2Lexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API phammer_v2Lexer hammer_v2LexerNew         
(pANTLR3_INPUT_STREAM instream)
{
	// See if we can create a new lexer with the standard constructor
	//
	return hammer_v2LexerNewSSD(instream, NULL);
}

/** \brief Create a new lexer called hammer_v2Lexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \param[state] state Previously created shared recognizer stat
 * \return 
 *     - Success phammer_v2Lexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API phammer_v2Lexer hammer_v2LexerNewSSD         
(pANTLR3_INPUT_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    phammer_v2Lexer ctx; // Context structure we will build and return

    ctx = (phammer_v2Lexer) ANTLR3_CALLOC(1, sizeof(hammer_v2Lexer));

    if  (ctx == NULL)
    {
        // Failed to allocate memory for lexer context
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * in base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 lexer function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function. 
     *
     * We don't use the macros defined in hammer_v2Lexer.h here so you can get a sense
     * of what goes where.
     */
    
    /* Create a base lexer, using the supplied input stream
     */
    ctx->pLexer	= antlr3LexerNewStream(ANTLR3_SIZE_HINT, instream, state);
    
    /* Check that we allocated the memory correctly
     */
    if	(ctx->pLexer == NULL)
    {
		ANTLR3_FREE(ctx);
		return  NULL;
    }
    /* Install the implementation of our hammer_v2Lexer interface
     */
    ctx->mT__41	= mT__41;
    ctx->mT__42	= mT__42;
    ctx->mT__43	= mT__43;
    ctx->mT__44	= mT__44;
    ctx->mT__45	= mT__45;
    ctx->mT__46	= mT__46;
    ctx->mT__47	= mT__47;
    ctx->mT__48	= mT__48;
    ctx->mT__49	= mT__49;
    ctx->mT__50	= mT__50;
    ctx->mT__51	= mT__51;
    ctx->mT__52	= mT__52;
    ctx->mT__53	= mT__53;
    ctx->mT__54	= mT__54;
    ctx->mPathUri	= mPathUri;
    ctx->mSlash	= mSlash;
    ctx->mDoubleSlash	= mDoubleSlash;
    ctx->mPublicTag	= mPublicTag;
    ctx->mLocal	= mLocal;
    ctx->mExplicit	= mExplicit;
    ctx->mQuestionMark	= mQuestionMark;
    ctx->mAsterix	= mAsterix;
    ctx->mDoubleAsterix	= mDoubleAsterix;
    ctx->mId	= mId;
    ctx->mSTRING	= mSTRING;
    ctx->mSTRING_ID	= mSTRING_ID;
    ctx->mSTRING_1	= mSTRING_1;
    ctx->mSTRING_ID1	= mSTRING_ID1;
    ctx->mCOMMENT	= mCOMMENT;
    ctx->mWS	= mWS;
    ctx->mTokens	= mTokens;
    
    /** When the nextToken() call is made to this lexer's pANTLR3_TOKEN_SOURCE
     *  it will call mTokens() in this generated code, and will pass it the ctx
     * pointer of this lexer, not the context of the base lexer, so store that now.
     */
    ctx->pLexer->ctx	    = ctx;
    
    /**Install the token matching function
     */
    ctx->pLexer->mTokens = (void (*) (void *))(mTokens);
    
    ctx->getGrammarFileName	= getGrammarFileName;
    ctx->free		= hammer_v2LexerFree;

    
    


    /* Return the newly built lexer to the caller
     */
    return  ctx;
}

/* =========================================================================
 * DFA tables for the lexer
 */
/** Static dfa state tables for Cyclic dfa:
 *    1:1: Tokens : ( T__41 | T__42 | T__43 | T__44 | T__45 | T__46 | T__47 | T__48 | T__49 | T__50 | T__51 | T__52 | T__53 | T__54 | PathUri | Slash | DoubleSlash | PublicTag | Local | Explicit | QuestionMark | Asterix | DoubleAsterix | Id | COMMENT | WS );
 */
static const ANTLR3_INT32 dfa7_eot[47] =
    {
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 22, -1, -1, 22, 28, -1, 
	22, 22, -1, 32, -1, -1, -1, -1, 22, -1, -1, 22, 22, -1, -1, 22, 22, 22, 
	22, 22, 22, -1, 42, 22, -1, 22, 22, 46, -1
    };
static const ANTLR3_INT32 dfa7_eof[47] =
    {
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1
    };
static const ANTLR3_INT32 dfa7_min[47] =
    {
	9, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 62, -1, -1, 105, 47, -1, 
	111, 120, -1, 42, -1, -1, -1, -1, 108, -1, -1, 99, 112, -1, -1, 101, 97, 
	108, 58, 108, 105, -1, 43, 99, -1, 105, 116, 43, -1
    };
static const ANTLR3_INT32 dfa7_max[47] =
    {
	125, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 62, -1, -1, 105, 47, -1, 
	111, 120, -1, 42, -1, -1, -1, -1, 108, -1, -1, 99, 112, -1, -1, 101, 97, 
	108, 58, 108, 105, -1, 122, 99, -1, 105, 116, 122, -1
    };
static const ANTLR3_INT32 dfa7_accept[47] =
    {
	-1, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, -1, 13, 14, -1, -1, 18, -1, -1, 
	21, -1, 24, 25, 26, 12, -1, 17, 16, -1, -1, 23, 22, -1, -1, -1, -1, -1, 
	-1, 15, -1, -1, 19, -1, -1, -1, 20
    };
static const ANTLR3_INT32 dfa7_special[47] =
    {	
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1
    };

/** Used when there is no transition table entry for a particular state */
#define dfa7_T_empty	    NULL

static const ANTLR3_INT32 dfa7_T0[] =
    {
	27
    };static const ANTLR3_INT32 dfa7_T1[] =
    {
	29
    };static const ANTLR3_INT32 dfa7_T2[] =
    {
	34
    };static const ANTLR3_INT32 dfa7_T3[] =
    {
	37
    };static const ANTLR3_INT32 dfa7_T4[] =
    {
	40
    };static const ANTLR3_INT32 dfa7_T5[] =
    {
	30
    };static const ANTLR3_INT32 dfa7_T6[] =
    {
	35
    };static const ANTLR3_INT32 dfa7_T7[] =
    {
	38
    };static const ANTLR3_INT32 dfa7_T8[] =
    {
	41
    };static const ANTLR3_INT32 dfa7_T9[] =
    {
	43
    };static const ANTLR3_INT32 dfa7_T10[] =
    {
	44
    };static const ANTLR3_INT32 dfa7_T11[] =
    {
	45
    };static const ANTLR3_INT32 dfa7_T12[] =
    {
	22, -1, 22, 22, -1, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, -1, -1, -1, 
	-1, -1, -1, -1, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 
	22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, -1, -1, -1, -1, 22, -1, 
	22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 
	22, 22, 22, 22, 22, 22, 22, 22
    };static const ANTLR3_INT32 dfa7_T13[] =
    {
	25
    };static const ANTLR3_INT32 dfa7_T14[] =
    {
	24, 24, -1, -1, 24, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, 24, -1, 22, 23, -1, -1, 14, 22, 10, 11, 21, 22, -1, 
	12, 22, 16, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 4, 1, 8, 5, 9, 20, 
	17, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 
	22, 22, 22, 22, 22, 22, 22, 22, 22, 2, -1, 3, -1, 22, -1, 22, 22, 22, 22, 
	19, 15, 22, 22, 22, 22, 22, 18, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 
	22, 22, 22, 22, 6, 13, 7
    };static const ANTLR3_INT32 dfa7_T15[] =
    {
	26
    };static const ANTLR3_INT32 dfa7_T16[] =
    {
	33
    };static const ANTLR3_INT32 dfa7_T17[] =
    {
	36
    };static const ANTLR3_INT32 dfa7_T18[] =
    {
	39
    };static const ANTLR3_INT32 dfa7_T19[] =
    {
	31
    };

/* Transition tables are a table of sub tables, with some tables
 * reused for efficiency.
 */
static const ANTLR3_INT32 * const dfa7_transitions[] =
{
    dfa7_T14, dfa7_T_empty, dfa7_T_empty, dfa7_T_empty, dfa7_T_empty, dfa7_T_empty, 
    dfa7_T_empty, dfa7_T_empty, dfa7_T_empty, dfa7_T_empty, dfa7_T_empty, 
    dfa7_T_empty, dfa7_T13, dfa7_T_empty, dfa7_T_empty, dfa7_T15, dfa7_T0, 
    dfa7_T_empty, dfa7_T1, dfa7_T5, dfa7_T_empty, dfa7_T19, dfa7_T_empty, 
    dfa7_T_empty, dfa7_T_empty, dfa7_T_empty, dfa7_T16, dfa7_T_empty, dfa7_T_empty, 
    dfa7_T2, dfa7_T6, dfa7_T_empty, dfa7_T_empty, dfa7_T17, dfa7_T3, dfa7_T7, 
    dfa7_T18, dfa7_T4, dfa7_T8, dfa7_T_empty, dfa7_T12, dfa7_T9, dfa7_T_empty, 
    dfa7_T10, dfa7_T11, dfa7_T12, dfa7_T_empty	
};


/* Declare tracking structure for Cyclic DFA 7
 */
static
ANTLR3_CYCLIC_DFA cdfa7
    =	{
	    7,		    /* Decision number of this dfa	    */
	    /* Which decision this represents:   */
	    (const pANTLR3_UCHAR)"1:1: Tokens : ( T__41 | T__42 | T__43 | T__44 | T__45 | T__46 | T__47 | T__48 | T__49 | T__50 | T__51 | T__52 | T__53 | T__54 | PathUri | Slash | DoubleSlash | PublicTag | Local | Explicit | QuestionMark | Asterix | DoubleAsterix | Id | COMMENT | WS );",	
	    (CDFA_SPECIAL_FUNC) antlr3dfaspecialStateTransition,	/* Default special state transition function	*/
	    antlr3dfaspecialTransition,		/* DFA specialTransition is currently just a default function in the runtime */
	    antlr3dfapredict,			/* DFA simulator function is in the runtime */
	    dfa7_eot,	    /* EOT table			    */
	    dfa7_eof,	    /* EOF table			    */
	    dfa7_min,	    /* Minimum tokens for each state    */
	    dfa7_max,	    /* Maximum tokens for each state    */
	    dfa7_accept,	/* Accept table			    */
	    dfa7_special,	/* Special transition states	    */
	    dfa7_transitions	/* Table of transition tables	    */

	};	    
/* End of Cyclic DFA 7
 * ---------------------
 */ 
/* =========================================================================
 * End of DFA tables for the lexer
 */ 

/* =========================================================================
 * Functions to match the lexer grammar defined tokens from the input stream
 */

//   Comes from: 7:7: ( ';' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__41
 *
 * Looks to match the characters the constitute the token T__41
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__41(phammer_v2Lexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = T__41;
       
    
    // hammer_v2.g:7:7: ( ';' )
    // hammer_v2.g:7:9: ';'
    {
        MATCHC(';'); 
        if  (HASEXCEPTION())
        {
            goto ruleT__41Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__41Ex; /* Prevent compiler warnings */
    ruleT__41Ex: ;

}
// $ANTLR end T__41

//   Comes from: 8:7: ( '[' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__42
 *
 * Looks to match the characters the constitute the token T__42
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__42(phammer_v2Lexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = T__42;
       
    
    // hammer_v2.g:8:7: ( '[' )
    // hammer_v2.g:8:9: '['
    {
        MATCHC('['); 
        if  (HASEXCEPTION())
        {
            goto ruleT__42Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__42Ex; /* Prevent compiler warnings */
    ruleT__42Ex: ;

}
// $ANTLR end T__42

//   Comes from: 9:7: ( ']' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__43
 *
 * Looks to match the characters the constitute the token T__43
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__43(phammer_v2Lexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = T__43;
       
    
    // hammer_v2.g:9:7: ( ']' )
    // hammer_v2.g:9:9: ']'
    {
        MATCHC(']'); 
        if  (HASEXCEPTION())
        {
            goto ruleT__43Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__43Ex; /* Prevent compiler warnings */
    ruleT__43Ex: ;

}
// $ANTLR end T__43

//   Comes from: 10:7: ( ':' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__44
 *
 * Looks to match the characters the constitute the token T__44
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__44(phammer_v2Lexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = T__44;
       
    
    // hammer_v2.g:10:7: ( ':' )
    // hammer_v2.g:10:9: ':'
    {
        MATCHC(':'); 
        if  (HASEXCEPTION())
        {
            goto ruleT__44Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__44Ex; /* Prevent compiler warnings */
    ruleT__44Ex: ;

}
// $ANTLR end T__44

//   Comes from: 11:7: ( '=' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__45
 *
 * Looks to match the characters the constitute the token T__45
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__45(phammer_v2Lexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = T__45;
       
    
    // hammer_v2.g:11:7: ( '=' )
    // hammer_v2.g:11:9: '='
    {
        MATCHC('='); 
        if  (HASEXCEPTION())
        {
            goto ruleT__45Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__45Ex; /* Prevent compiler warnings */
    ruleT__45Ex: ;

}
// $ANTLR end T__45

//   Comes from: 12:7: ( '{' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__46
 *
 * Looks to match the characters the constitute the token T__46
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__46(phammer_v2Lexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = T__46;
       
    
    // hammer_v2.g:12:7: ( '{' )
    // hammer_v2.g:12:9: '{'
    {
        MATCHC('{'); 
        if  (HASEXCEPTION())
        {
            goto ruleT__46Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__46Ex; /* Prevent compiler warnings */
    ruleT__46Ex: ;

}
// $ANTLR end T__46

//   Comes from: 13:7: ( '}' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__47
 *
 * Looks to match the characters the constitute the token T__47
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__47(phammer_v2Lexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = T__47;
       
    
    // hammer_v2.g:13:7: ( '}' )
    // hammer_v2.g:13:9: '}'
    {
        MATCHC('}'); 
        if  (HASEXCEPTION())
        {
            goto ruleT__47Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__47Ex; /* Prevent compiler warnings */
    ruleT__47Ex: ;

}
// $ANTLR end T__47

//   Comes from: 14:7: ( '<' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__48
 *
 * Looks to match the characters the constitute the token T__48
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__48(phammer_v2Lexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = T__48;
       
    
    // hammer_v2.g:14:7: ( '<' )
    // hammer_v2.g:14:9: '<'
    {
        MATCHC('<'); 
        if  (HASEXCEPTION())
        {
            goto ruleT__48Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__48Ex; /* Prevent compiler warnings */
    ruleT__48Ex: ;

}
// $ANTLR end T__48

//   Comes from: 15:7: ( '>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__49
 *
 * Looks to match the characters the constitute the token T__49
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__49(phammer_v2Lexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = T__49;
       
    
    // hammer_v2.g:15:7: ( '>' )
    // hammer_v2.g:15:9: '>'
    {
        MATCHC('>'); 
        if  (HASEXCEPTION())
        {
            goto ruleT__49Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__49Ex; /* Prevent compiler warnings */
    ruleT__49Ex: ;

}
// $ANTLR end T__49

//   Comes from: 16:7: ( '(' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__50
 *
 * Looks to match the characters the constitute the token T__50
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__50(phammer_v2Lexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = T__50;
       
    
    // hammer_v2.g:16:7: ( '(' )
    // hammer_v2.g:16:9: '('
    {
        MATCHC('('); 
        if  (HASEXCEPTION())
        {
            goto ruleT__50Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__50Ex; /* Prevent compiler warnings */
    ruleT__50Ex: ;

}
// $ANTLR end T__50

//   Comes from: 17:7: ( ')' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__51
 *
 * Looks to match the characters the constitute the token T__51
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__51(phammer_v2Lexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = T__51;
       
    
    // hammer_v2.g:17:7: ( ')' )
    // hammer_v2.g:17:9: ')'
    {
        MATCHC(')'); 
        if  (HASEXCEPTION())
        {
            goto ruleT__51Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__51Ex; /* Prevent compiler warnings */
    ruleT__51Ex: ;

}
// $ANTLR end T__51

//   Comes from: 18:7: ( '->' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__52
 *
 * Looks to match the characters the constitute the token T__52
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__52(phammer_v2Lexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = T__52;
       
    
    // hammer_v2.g:18:7: ( '->' )
    // hammer_v2.g:18:9: '->'
    {
        MATCHS(lit_1); 
        if  (HASEXCEPTION())
        {
            goto ruleT__52Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__52Ex; /* Prevent compiler warnings */
    ruleT__52Ex: ;

}
// $ANTLR end T__52

//   Comes from: 19:7: ( '||' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__53
 *
 * Looks to match the characters the constitute the token T__53
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__53(phammer_v2Lexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = T__53;
       
    
    // hammer_v2.g:19:7: ( '||' )
    // hammer_v2.g:19:9: '||'
    {
        MATCHS(lit_2); 
        if  (HASEXCEPTION())
        {
            goto ruleT__53Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__53Ex; /* Prevent compiler warnings */
    ruleT__53Ex: ;

}
// $ANTLR end T__53

//   Comes from: 20:7: ( '&&' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__54
 *
 * Looks to match the characters the constitute the token T__54
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__54(phammer_v2Lexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = T__54;
       
    
    // hammer_v2.g:20:7: ( '&&' )
    // hammer_v2.g:20:9: '&&'
    {
        MATCHS(lit_3); 
        if  (HASEXCEPTION())
        {
            goto ruleT__54Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__54Ex; /* Prevent compiler warnings */
    ruleT__54Ex: ;

}
// $ANTLR end T__54

//   Comes from: 236:9: ( 'file://' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start PathUri
 *
 * Looks to match the characters the constitute the token PathUri
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mPathUri(phammer_v2Lexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = PathUri;
       
    
    // hammer_v2.g:236:9: ( 'file://' )
    // hammer_v2.g:236:11: 'file://'
    {
        MATCHS(lit_4); 
        if  (HASEXCEPTION())
        {
            goto rulePathUriEx;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto rulePathUriEx; /* Prevent compiler warnings */
    rulePathUriEx: ;

}
// $ANTLR end PathUri

//   Comes from: 237:7: ( '/' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start Slash
 *
 * Looks to match the characters the constitute the token Slash
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mSlash(phammer_v2Lexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = Slash;
       
    
    // hammer_v2.g:237:7: ( '/' )
    // hammer_v2.g:237:9: '/'
    {
        MATCHC('/'); 
        if  (HASEXCEPTION())
        {
            goto ruleSlashEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleSlashEx; /* Prevent compiler warnings */
    ruleSlashEx: ;

}
// $ANTLR end Slash

//   Comes from: 238:13: ( '//' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start DoubleSlash
 *
 * Looks to match the characters the constitute the token DoubleSlash
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mDoubleSlash(phammer_v2Lexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = DoubleSlash;
       
    
    // hammer_v2.g:238:13: ( '//' )
    // hammer_v2.g:238:15: '//'
    {
        MATCHS(lit_5); 
        if  (HASEXCEPTION())
        {
            goto ruleDoubleSlashEx;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleDoubleSlashEx; /* Prevent compiler warnings */
    ruleDoubleSlashEx: ;

}
// $ANTLR end DoubleSlash

//   Comes from: 239:11: ( '@' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start PublicTag
 *
 * Looks to match the characters the constitute the token PublicTag
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mPublicTag(phammer_v2Lexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = PublicTag;
       
    
    // hammer_v2.g:239:11: ( '@' )
    // hammer_v2.g:239:13: '@'
    {
        MATCHC('@'); 
        if  (HASEXCEPTION())
        {
            goto rulePublicTagEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto rulePublicTagEx; /* Prevent compiler warnings */
    rulePublicTagEx: ;

}
// $ANTLR end PublicTag

//   Comes from: 240:7: ( 'local' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start Local
 *
 * Looks to match the characters the constitute the token Local
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mLocal(phammer_v2Lexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = Local;
       
    
    // hammer_v2.g:240:7: ( 'local' )
    // hammer_v2.g:240:9: 'local'
    {
        MATCHS(lit_6); 
        if  (HASEXCEPTION())
        {
            goto ruleLocalEx;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleLocalEx; /* Prevent compiler warnings */
    ruleLocalEx: ;

}
// $ANTLR end Local

//   Comes from: 241:10: ( 'explicit' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start Explicit
 *
 * Looks to match the characters the constitute the token Explicit
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mExplicit(phammer_v2Lexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = Explicit;
       
    
    // hammer_v2.g:241:10: ( 'explicit' )
    // hammer_v2.g:241:12: 'explicit'
    {
        MATCHS(lit_7); 
        if  (HASEXCEPTION())
        {
            goto ruleExplicitEx;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleExplicitEx; /* Prevent compiler warnings */
    ruleExplicitEx: ;

}
// $ANTLR end Explicit

//   Comes from: 242:14: ( '?' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start QuestionMark
 *
 * Looks to match the characters the constitute the token QuestionMark
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mQuestionMark(phammer_v2Lexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = QuestionMark;
       
    
    // hammer_v2.g:242:14: ( '?' )
    // hammer_v2.g:242:16: '?'
    {
        MATCHC('?'); 
        if  (HASEXCEPTION())
        {
            goto ruleQuestionMarkEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleQuestionMarkEx; /* Prevent compiler warnings */
    ruleQuestionMarkEx: ;

}
// $ANTLR end QuestionMark

//   Comes from: 243:9: ( '*' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start Asterix
 *
 * Looks to match the characters the constitute the token Asterix
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mAsterix(phammer_v2Lexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = Asterix;
       
    
    // hammer_v2.g:243:9: ( '*' )
    // hammer_v2.g:243:11: '*'
    {
        MATCHC('*'); 
        if  (HASEXCEPTION())
        {
            goto ruleAsterixEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleAsterixEx; /* Prevent compiler warnings */
    ruleAsterixEx: ;

}
// $ANTLR end Asterix

//   Comes from: 244:15: ( '**' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start DoubleAsterix
 *
 * Looks to match the characters the constitute the token DoubleAsterix
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mDoubleAsterix(phammer_v2Lexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = DoubleAsterix;
       
    
    // hammer_v2.g:244:15: ( '**' )
    // hammer_v2.g:244:17: '**'
    {
        MATCHS(lit_8); 
        if  (HASEXCEPTION())
        {
            goto ruleDoubleAsterixEx;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleDoubleAsterixEx; /* Prevent compiler warnings */
    ruleDoubleAsterixEx: ;

}
// $ANTLR end DoubleAsterix

//   Comes from: 246:4: ( ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '.' | '-' | '_' | '+' )+ | STRING | STRING_1 )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start Id
 *
 * Looks to match the characters the constitute the token Id
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mId(phammer_v2Lexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = Id;
       
    
    {
        //  hammer_v2.g:246:4: ( ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '.' | '-' | '_' | '+' )+ | STRING | STRING_1 )
        
        ANTLR3_UINT32 alt2;

        alt2=3;

        switch ( LA(1) ) 
        {
        case '+':
        case '-':
        case '.':
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':
        case 'A':
        case 'B':
        case 'C':
        case 'D':
        case 'E':
        case 'F':
        case 'G':
        case 'H':
        case 'I':
        case 'J':
        case 'K':
        case 'L':
        case 'M':
        case 'N':
        case 'O':
        case 'P':
        case 'Q':
        case 'R':
        case 'S':
        case 'T':
        case 'U':
        case 'V':
        case 'W':
        case 'X':
        case 'Y':
        case 'Z':
        case '_':
        case 'a':
        case 'b':
        case 'c':
        case 'd':
        case 'e':
        case 'f':
        case 'g':
        case 'h':
        case 'i':
        case 'j':
        case 'k':
        case 'l':
        case 'm':
        case 'n':
        case 'o':
        case 'p':
        case 'q':
        case 'r':
        case 's':
        case 't':
        case 'u':
        case 'v':
        case 'w':
        case 'x':
        case 'y':
        case 'z':
        	{
        		alt2=1;
        	}
            break;
        case '"':
        	{
        		alt2=2;
        	}
            break;
        case '\'':
        	{
        		alt2=3;
        	}
            break;

        default:
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            EXCEPTION->message      = (void *)"";
            EXCEPTION->decisionNum  = 2;
            EXCEPTION->state        = 0;


            goto ruleIdEx;
        }

        switch (alt2) 
        {
    	case 1:
    	    // hammer_v2.g:246:6: ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '.' | '-' | '_' | '+' )+
    	    {
    	        // hammer_v2.g:246:6: ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '.' | '-' | '_' | '+' )+
    	        {
    	            int cnt1=0;

    	            for (;;)
    	            {
    	                int alt1=2;
    	        	{
    	        	   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
    	        	    */
    	        	    int LA1_0 = LA(1);
    	        	    if ( (LA1_0 == '+' || ((LA1_0 >= '-') && (LA1_0 <= '.')) || ((LA1_0 >= '0') && (LA1_0 <= '9')) || ((LA1_0 >= 'A') && (LA1_0 <= 'Z')) || LA1_0 == '_' || ((LA1_0 >= 'a') && (LA1_0 <= 'z'))) ) 
    	        	    {
    	        	        alt1=1;
    	        	    }

    	        	}
    	        	switch (alt1) 
    	        	{
    	        	    case 1:
    	        	        // hammer_v2.g:
    	        	        {
    	        	            if ( LA(1) == '+' || ((LA(1) >= '-') && (LA(1) <= '.')) || ((LA(1) >= '0') && (LA(1) <= '9')) || ((LA(1) >= 'A') && (LA(1) <= 'Z')) || LA(1) == '_' || ((LA(1) >= 'a') && (LA(1) <= 'z')) )
    	        	            {
    	        	                CONSUME();

    	        	            }
    	        	            else 
    	        	            {
    	        	                CONSTRUCTEX();
    	        	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
    	        	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

    	        	                LRECOVER();    goto ruleIdEx;
    	        	            }


    	        	        }
    	        	        break;

    	        	    default:
    	        	    
    	        		if ( cnt1 >= 1 )
    	        		{
    	        		    goto loop1;
    	        		}
    	        		/* mismatchedSetEx()
    	        		 */
    	        		CONSTRUCTEX();
    	        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
    	        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


    	        		goto ruleIdEx;
    	        	}
    	        	cnt1++;
    	            }
    	            loop1: ;	/* Jump to here if this rule does not match */
    	        }

    	    }
    	    break;
    	case 2:
    	    // hammer_v2.g:247:6: STRING
    	    {
    	        /* 247:6: STRING */
    	        mSTRING(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleIdEx;
    	        }


    	    }
    	    break;
    	case 3:
    	    // hammer_v2.g:247:15: STRING_1
    	    {
    	        /* 247:15: STRING_1 */
    	        mSTRING_1(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleIdEx;
    	        }


    	    }
    	    break;

        }
    }
	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleIdEx; /* Prevent compiler warnings */
    ruleIdEx: ;

}
// $ANTLR end Id

//   Comes from: 250:8: ( '\"' STRING_ID '\"' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start STRING
 *
 * Looks to match the characters the constitute the token STRING
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mSTRING(phammer_v2Lexer ctx)
{
	ANTLR3_UINT32	_type;

        
    // hammer_v2.g:250:8: ( '\"' STRING_ID '\"' )
    // hammer_v2.g:250:10: '\"' STRING_ID '\"'
    {
        MATCHC('"'); 
        if  (HASEXCEPTION())
        {
            goto ruleSTRINGEx;
        }

        /* 250:10: '\"' STRING_ID '\"' */
        mSTRING_ID(ctx ); 
        if  (HASEXCEPTION())
        {
            goto ruleSTRINGEx;
        }

        MATCHC('"'); 
        if  (HASEXCEPTION())
        {
            goto ruleSTRINGEx;
        }


    }



    // This is where rules clean up and exit
    //
    goto ruleSTRINGEx; /* Prevent compiler warnings */
    ruleSTRINGEx: ;

}
// $ANTLR end STRING

//   Comes from: 252:11: ( ( '\\\\\"' | ~ ( '\"' | '\\n' | '\\r' ) )* )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start STRING_ID
 *
 * Looks to match the characters the constitute the token STRING_ID
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mSTRING_ID(phammer_v2Lexer ctx)
{
	ANTLR3_UINT32	_type;

        
    // hammer_v2.g:252:11: ( ( '\\\\\"' | ~ ( '\"' | '\\n' | '\\r' ) )* )
    // hammer_v2.g:252:13: ( '\\\\\"' | ~ ( '\"' | '\\n' | '\\r' ) )*
    {

        // hammer_v2.g:252:13: ( '\\\\\"' | ~ ( '\"' | '\\n' | '\\r' ) )*

        for (;;)
        {
            int alt3=3;
            {
               /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                */
                int LA3_0 = LA(1);
                if ( (LA3_0 == '\\') ) 
                {
                    {
                       /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                        */
                        int LA3_2 = LA(2);
                        if ( (LA3_2 == '"') ) 
                        {
                            alt3=1;
                        }

                        
                        else 
                        {
                    	alt3=2;
                        }

                    }
                }
                else if ( (((LA3_0 >= 0x0000) && (LA3_0 <= '\t')) || ((LA3_0 >= 0x000B) && (LA3_0 <= '\f')) || ((LA3_0 >= 0x000E) && (LA3_0 <= '!')) || ((LA3_0 >= '#') && (LA3_0 <= '[')) || ((LA3_0 >= ']') && (LA3_0 <= 0xFFFF))) ) 
                {
                    alt3=2;
                }

            }
            switch (alt3) 
            {
        	case 1:
        	    // hammer_v2.g:252:14: '\\\\\"'
        	    {
        	        MATCHS(lit_9); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleSTRING_IDEx;
        	        }



        	    }
        	    break;
        	case 2:
        	    // hammer_v2.g:252:22: ~ ( '\"' | '\\n' | '\\r' )
        	    {
        	        if ( ((LA(1) >= 0x0000) && (LA(1) <= '\t')) || ((LA(1) >= 0x000B) && (LA(1) <= '\f')) || ((LA(1) >= 0x000E) && (LA(1) <= '!')) || ((LA(1) >= '#') && (LA(1) <= 0xFFFF)) )
        	        {
        	            CONSUME();

        	        }
        	        else 
        	        {
        	            CONSTRUCTEX();
        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	            LRECOVER();    goto ruleSTRING_IDEx;
        	        }


        	    }
        	    break;

        	default:
        	    goto loop3;	/* break out of the loop */
        	    break;
            }
        }
        loop3: ; /* Jump out to here if this rule does not match */


    }



    // This is where rules clean up and exit
    //
    goto ruleSTRING_IDEx; /* Prevent compiler warnings */
    ruleSTRING_IDEx: ;

}
// $ANTLR end STRING_ID

//   Comes from: 254:9: ( '\\'' STRING_ID1 '\\'' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start STRING_1
 *
 * Looks to match the characters the constitute the token STRING_1
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mSTRING_1(phammer_v2Lexer ctx)
{
	ANTLR3_UINT32	_type;

        
    // hammer_v2.g:254:9: ( '\\'' STRING_ID1 '\\'' )
    // hammer_v2.g:254:11: '\\'' STRING_ID1 '\\''
    {
        MATCHC('\''); 
        if  (HASEXCEPTION())
        {
            goto ruleSTRING_1Ex;
        }

        /* 254:11: '\\'' STRING_ID1 '\\'' */
        mSTRING_ID1(ctx ); 
        if  (HASEXCEPTION())
        {
            goto ruleSTRING_1Ex;
        }

        MATCHC('\''); 
        if  (HASEXCEPTION())
        {
            goto ruleSTRING_1Ex;
        }


    }



    // This is where rules clean up and exit
    //
    goto ruleSTRING_1Ex; /* Prevent compiler warnings */
    ruleSTRING_1Ex: ;

}
// $ANTLR end STRING_1

//   Comes from: 256:12: ( ( '\\\\\\'' | ~ ( '\\'' | '\\n' | '\\r' ) )* )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start STRING_ID1
 *
 * Looks to match the characters the constitute the token STRING_ID1
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mSTRING_ID1(phammer_v2Lexer ctx)
{
	ANTLR3_UINT32	_type;

        
    // hammer_v2.g:256:12: ( ( '\\\\\\'' | ~ ( '\\'' | '\\n' | '\\r' ) )* )
    // hammer_v2.g:256:14: ( '\\\\\\'' | ~ ( '\\'' | '\\n' | '\\r' ) )*
    {

        // hammer_v2.g:256:14: ( '\\\\\\'' | ~ ( '\\'' | '\\n' | '\\r' ) )*

        for (;;)
        {
            int alt4=3;
            {
               /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                */
                int LA4_0 = LA(1);
                if ( (LA4_0 == '\\') ) 
                {
                    {
                       /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                        */
                        int LA4_2 = LA(2);
                        if ( (LA4_2 == '\'') ) 
                        {
                            alt4=1;
                        }

                        
                        else 
                        {
                    	alt4=2;
                        }

                    }
                }
                else if ( (((LA4_0 >= 0x0000) && (LA4_0 <= '\t')) || ((LA4_0 >= 0x000B) && (LA4_0 <= '\f')) || ((LA4_0 >= 0x000E) && (LA4_0 <= '&')) || ((LA4_0 >= '(') && (LA4_0 <= '[')) || ((LA4_0 >= ']') && (LA4_0 <= 0xFFFF))) ) 
                {
                    alt4=2;
                }

            }
            switch (alt4) 
            {
        	case 1:
        	    // hammer_v2.g:256:15: '\\\\\\''
        	    {
        	        MATCHS(lit_10); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleSTRING_ID1Ex;
        	        }



        	    }
        	    break;
        	case 2:
        	    // hammer_v2.g:256:24: ~ ( '\\'' | '\\n' | '\\r' )
        	    {
        	        if ( ((LA(1) >= 0x0000) && (LA(1) <= '\t')) || ((LA(1) >= 0x000B) && (LA(1) <= '\f')) || ((LA(1) >= 0x000E) && (LA(1) <= '&')) || ((LA(1) >= '(') && (LA(1) <= 0xFFFF)) )
        	        {
        	            CONSUME();

        	        }
        	        else 
        	        {
        	            CONSTRUCTEX();
        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	            LRECOVER();    goto ruleSTRING_ID1Ex;
        	        }


        	    }
        	    break;

        	default:
        	    goto loop4;	/* break out of the loop */
        	    break;
            }
        }
        loop4: ; /* Jump out to here if this rule does not match */


    }



    // This is where rules clean up and exit
    //
    goto ruleSTRING_ID1Ex; /* Prevent compiler warnings */
    ruleSTRING_ID1Ex: ;

}
// $ANTLR end STRING_ID1

//   Comes from: 258:9: ( '#' (~ ( '\\n' | '\\r' ) )* ( '\\n' | '\\r' )? )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start COMMENT
 *
 * Looks to match the characters the constitute the token COMMENT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mCOMMENT(phammer_v2Lexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = COMMENT;
       
    
    // hammer_v2.g:258:9: ( '#' (~ ( '\\n' | '\\r' ) )* ( '\\n' | '\\r' )? )
    // hammer_v2.g:258:11: '#' (~ ( '\\n' | '\\r' ) )* ( '\\n' | '\\r' )?
    {
        MATCHC('#'); 
        if  (HASEXCEPTION())
        {
            goto ruleCOMMENTEx;
        }


        // hammer_v2.g:258:15: (~ ( '\\n' | '\\r' ) )*

        for (;;)
        {
            int alt5=2;
            {
               /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                */
                int LA5_0 = LA(1);
                if ( (((LA5_0 >= 0x0000) && (LA5_0 <= '\t')) || ((LA5_0 >= 0x000B) && (LA5_0 <= '\f')) || ((LA5_0 >= 0x000E) && (LA5_0 <= 0xFFFF))) ) 
                {
                    alt5=1;
                }

            }
            switch (alt5) 
            {
        	case 1:
        	    // hammer_v2.g:258:16: ~ ( '\\n' | '\\r' )
        	    {
        	        if ( ((LA(1) >= 0x0000) && (LA(1) <= '\t')) || ((LA(1) >= 0x000B) && (LA(1) <= '\f')) || ((LA(1) >= 0x000E) && (LA(1) <= 0xFFFF)) )
        	        {
        	            CONSUME();

        	        }
        	        else 
        	        {
        	            CONSTRUCTEX();
        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	            LRECOVER();    goto ruleCOMMENTEx;
        	        }


        	    }
        	    break;

        	default:
        	    goto loop5;	/* break out of the loop */
        	    break;
            }
        }
        loop5: ; /* Jump out to here if this rule does not match */


        // hammer_v2.g:258:33: ( '\\n' | '\\r' )?
        {
            int alt6=2;
            {
                int LA6_0 = LA(1);
                if ( (LA6_0 == '\n' || LA6_0 == '\r') ) 
                {
                    alt6=1;
                }
            }
            switch (alt6) 
            {
        	case 1:
        	    // hammer_v2.g:
        	    {
        	        if ( LA(1) == '\n' || LA(1) == '\r' )
        	        {
        	            CONSUME();

        	        }
        	        else 
        	        {
        	            CONSTRUCTEX();
        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	            LRECOVER();    goto ruleCOMMENTEx;
        	        }


        	    }
        	    break;

            }
        }
        {
             LEXSTATE->channel = HIDDEN; 
        }

    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleCOMMENTEx; /* Prevent compiler warnings */
    ruleCOMMENTEx: ;

}
// $ANTLR end COMMENT

//   Comes from: 260:4: ( ( ' ' | '\\n' | '\\r' | '\\t' ) )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start WS
 *
 * Looks to match the characters the constitute the token WS
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mWS(phammer_v2Lexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = WS;
       
    
    // hammer_v2.g:260:4: ( ( ' ' | '\\n' | '\\r' | '\\t' ) )
    // hammer_v2.g:260:6: ( ' ' | '\\n' | '\\r' | '\\t' )
    {
        if ( ((LA(1) >= '\t') && (LA(1) <= '\n')) || LA(1) == '\r' || LA(1) == ' ' )
        {
            CONSUME();

        }
        else 
        {
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

            LRECOVER();    goto ruleWSEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleWSEx; /* Prevent compiler warnings */
    ruleWSEx: ;

}
// $ANTLR end WS

/** This is the entry point in to the lexer from an object that
 *  wants to generate the next token, such as a pCOMMON_TOKEN_STREAM
 */
static void 
mTokens(phammer_v2Lexer ctx)
{
    {
        //  hammer_v2.g:1:8: ( T__41 | T__42 | T__43 | T__44 | T__45 | T__46 | T__47 | T__48 | T__49 | T__50 | T__51 | T__52 | T__53 | T__54 | PathUri | Slash | DoubleSlash | PublicTag | Local | Explicit | QuestionMark | Asterix | DoubleAsterix | Id | COMMENT | WS )
        
        ANTLR3_UINT32 alt7;

        alt7=26;

        alt7 = cdfa7.predict(ctx, RECOGNIZER, ISTREAM, &cdfa7);
        if  (HASEXCEPTION())
        {
            goto ruleTokensEx;
        }

        switch (alt7) 
        {
    	case 1:
    	    // hammer_v2.g:1:10: T__41
    	    {
    	        /* 1:10: T__41 */
    	        mT__41(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 2:
    	    // hammer_v2.g:1:16: T__42
    	    {
    	        /* 1:16: T__42 */
    	        mT__42(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 3:
    	    // hammer_v2.g:1:22: T__43
    	    {
    	        /* 1:22: T__43 */
    	        mT__43(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 4:
    	    // hammer_v2.g:1:28: T__44
    	    {
    	        /* 1:28: T__44 */
    	        mT__44(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 5:
    	    // hammer_v2.g:1:34: T__45
    	    {
    	        /* 1:34: T__45 */
    	        mT__45(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 6:
    	    // hammer_v2.g:1:40: T__46
    	    {
    	        /* 1:40: T__46 */
    	        mT__46(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 7:
    	    // hammer_v2.g:1:46: T__47
    	    {
    	        /* 1:46: T__47 */
    	        mT__47(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 8:
    	    // hammer_v2.g:1:52: T__48
    	    {
    	        /* 1:52: T__48 */
    	        mT__48(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 9:
    	    // hammer_v2.g:1:58: T__49
    	    {
    	        /* 1:58: T__49 */
    	        mT__49(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 10:
    	    // hammer_v2.g:1:64: T__50
    	    {
    	        /* 1:64: T__50 */
    	        mT__50(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 11:
    	    // hammer_v2.g:1:70: T__51
    	    {
    	        /* 1:70: T__51 */
    	        mT__51(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 12:
    	    // hammer_v2.g:1:76: T__52
    	    {
    	        /* 1:76: T__52 */
    	        mT__52(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 13:
    	    // hammer_v2.g:1:82: T__53
    	    {
    	        /* 1:82: T__53 */
    	        mT__53(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 14:
    	    // hammer_v2.g:1:88: T__54
    	    {
    	        /* 1:88: T__54 */
    	        mT__54(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 15:
    	    // hammer_v2.g:1:94: PathUri
    	    {
    	        /* 1:94: PathUri */
    	        mPathUri(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 16:
    	    // hammer_v2.g:1:102: Slash
    	    {
    	        /* 1:102: Slash */
    	        mSlash(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 17:
    	    // hammer_v2.g:1:108: DoubleSlash
    	    {
    	        /* 1:108: DoubleSlash */
    	        mDoubleSlash(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 18:
    	    // hammer_v2.g:1:120: PublicTag
    	    {
    	        /* 1:120: PublicTag */
    	        mPublicTag(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 19:
    	    // hammer_v2.g:1:130: Local
    	    {
    	        /* 1:130: Local */
    	        mLocal(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 20:
    	    // hammer_v2.g:1:136: Explicit
    	    {
    	        /* 1:136: Explicit */
    	        mExplicit(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 21:
    	    // hammer_v2.g:1:145: QuestionMark
    	    {
    	        /* 1:145: QuestionMark */
    	        mQuestionMark(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 22:
    	    // hammer_v2.g:1:158: Asterix
    	    {
    	        /* 1:158: Asterix */
    	        mAsterix(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 23:
    	    // hammer_v2.g:1:166: DoubleAsterix
    	    {
    	        /* 1:166: DoubleAsterix */
    	        mDoubleAsterix(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 24:
    	    // hammer_v2.g:1:180: Id
    	    {
    	        /* 1:180: Id */
    	        mId(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 25:
    	    // hammer_v2.g:1:183: COMMENT
    	    {
    	        /* 1:183: COMMENT */
    	        mCOMMENT(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 26:
    	    // hammer_v2.g:1:191: WS
    	    {
    	        /* 1:191: WS */
    	        mWS(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;

        }
    }

    
    goto ruleTokensEx; /* Prevent compiler warnings */
ruleTokensEx: ;
}

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */
/* End of Lexer code
 * ================================================
 * ================================================
 */ 


/* End of code
 * =============================================================================
 */
