/** \file
 *  This C source file was generated by $ANTLR version 3.1.1
 *
 *     -  From the grammar source file : hammer_sema.gt
 *     -                            On : 2010-07-30 18:32:32
 *     -           for the tree parser : hammer_semaTreeParser *
 * Editing it, at least manually, is not wise. 
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/

/* =============================================================================
 * This is what the grammar programmer asked us to put at the top of every file.
 */

#include <hammer/sema/actions.h>
#include <hammer/parscore/identifier.h>
#define SEMA static_cast<const hammer::sema::actions*>(PARSER->super)

/* End of Header action.
 * =============================================================================
 */
/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "hammer_sema.h"
/* ----------------------------------------- */





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */
 
#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   phammer_sema_##scope##_SCOPE
#define SCOPE_STACK(scope)  phammer_sema_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->phammer_sema_##scope##Top
#define	SCOPE_SIZE(scope)			(ctx->SCOPE_STACK(scope)->size(ctx->SCOPE_STACK(scope)))
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

/* Macros for accessing things in the parser
 */
 
#undef	    PARSER
#undef	    RECOGNIZER		    
#undef	    HAVEPARSEDRULE
#undef	    INPUT
#undef	    STRSTREAM
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    MATCHT
#undef	    MATCHANYT
#undef	    FOLLOWSTACK
#undef	    FOLLOWPUSH
#undef	    FOLLOWPOP
#undef	    PRECOVER
#undef	    PREPORTERROR
#undef	    LA
#undef	    LT
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    PERRORRECOVERY
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    RECOVERFROMMISMATCHEDSET
#undef	    RECOVERFROMMISMATCHEDELEMENT
#undef	    BACKTRACKING
#undef      ADAPTOR
#undef	    RULEMEMO		
#undef		SEEK    
#undef		INDEX
#undef		DBG

#define	    PARSER							ctx->pTreeParser  
#define	    RECOGNIZER						PARSER->rec
#define		PSRSTATE						RECOGNIZER->state
#define	    HAVEPARSEDRULE(r)				RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define	    INPUT							PARSER->ctnstream
#define		ISTREAM							INPUT->tnstream->istream
#define	    STRSTREAM						INPUT->tnstream
#define	    HASEXCEPTION()					(PSRSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION						PSRSTATE->exception
#define	    MATCHT(t, fs)					RECOGNIZER->match(RECOGNIZER, t, fs)
#define	    MATCHANYT()						RECOGNIZER->matchAny(RECOGNIZER)
#define	    FOLLOWSTACK					    PSRSTATE->following
#define	    FOLLOWPUSH(x)					FOLLOWSTACK->push(FOLLOWSTACK, ((void *)(&(x))), NULL)
#define	    FOLLOWPOP()						FOLLOWSTACK->pop(FOLLOWSTACK)
#define	    PRECOVER()						RECOGNIZER->recover(RECOGNIZER)
#define	    PREPORTERROR()					RECOGNIZER->reportError(RECOGNIZER)
#define	    LA(n)							ISTREAM->_LA(ISTREAM, n)
#define	    LT(n)							INPUT->tnstream->_LT(INPUT->tnstream, n)
#define	    CONSTRUCTEX()					RECOGNIZER->exConstruct(RECOGNIZER)
#define	    CONSUME()						ISTREAM->consume(ISTREAM)
#define	    MARK()							ISTREAM->mark(ISTREAM)
#define	    REWIND(m)						ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()					ISTREAM->rewindLast(ISTREAM)
#define	    PERRORRECOVERY					PSRSTATE->errorRecovery
#define	    FAILEDFLAG						PSRSTATE->failed
#define	    HASFAILED()						(FAILEDFLAG == ANTLR3_TRUE)
#define	    BACKTRACKING					PSRSTATE->backtracking
#define	    RECOVERFROMMISMATCHEDSET(s)		RECOGNIZER->recoverFromMismatchedSet(RECOGNIZER, s)
#define	    RECOVERFROMMISMATCHEDELEMENT(e)	RECOGNIZER->recoverFromMismatchedElement(RECOGNIZER, s)
#define     ADAPTOR                         INPUT->adaptor
#define		RULEMEMO						PSRSTATE->ruleMemo
#define		SEEK(n)							ISTREAM->seek(ISTREAM, n)
#define		INDEX()							ISTREAM->index(ISTREAM)
#define		DBG								RECOGNIZER->debugger


#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */



/** \brief Table of all token names in symbolic order, mainly used for
 *         error reporting.
 */
pANTLR3_UINT8   hammer_semaTokenNames[33+4]
     = {
        (pANTLR3_UINT8) "<invalid>",       /* String to print to indicate an invalid token */
        (pANTLR3_UINT8) "<EOR>",
        (pANTLR3_UINT8) "<DOWN>", 
        (pANTLR3_UINT8) "<UP>", 
        (pANTLR3_UINT8) "HAMFILE",
        (pANTLR3_UINT8) "EXPLICIT_PROJECT_DEF",
        (pANTLR3_UINT8) "IMPLICIT_PROJECT_DEF",
        (pANTLR3_UINT8) "TARGET_DECL_OR_RULE_CALL",
        (pANTLR3_UINT8) "TARGET_REF",
        (pANTLR3_UINT8) "TARGET_NAME",
        (pANTLR3_UINT8) "ARGUMENTS",
        (pANTLR3_UINT8) "EXPRESSION",
        (pANTLR3_UINT8) "EMPTY_EXPRESSION",
        (pANTLR3_UINT8) "LIST_OF",
        (pANTLR3_UINT8) "PATH_LIKE_SEQ",
        (pANTLR3_UINT8) "FEATURE_SET",
        (pANTLR3_UINT8) "FEATURE",
        (pANTLR3_UINT8) "PUBLIC_TAG",
        (pANTLR3_UINT8) "CONDITION",
        (pANTLR3_UINT8) "WS",
        (pANTLR3_UINT8) "ID",
        (pANTLR3_UINT8) "SLASH",
        (pANTLR3_UINT8) "STRING",
        (pANTLR3_UINT8) "COLON",
        (pANTLR3_UINT8) "STRING_ID",
        (pANTLR3_UINT8) "COMMENT",
        (pANTLR3_UINT8) "'project'",
        (pANTLR3_UINT8) "';'",
        (pANTLR3_UINT8) "','",
        (pANTLR3_UINT8) "'<'",
        (pANTLR3_UINT8) "'>'",
        (pANTLR3_UINT8) "'('",
        (pANTLR3_UINT8) "')'",
        (pANTLR3_UINT8) "'//'",
        (pANTLR3_UINT8) "'['",
        (pANTLR3_UINT8) "']'",
        (pANTLR3_UINT8) "'@'"
       };

        

// Forward declare the locally static matching functions we have generated.
//
static const hammer::ast::hamfile*	hamfile    (phammer_sema ctx);
static const hammer::ast::project_def*	project_def    (phammer_sema ctx);
static void	arguments    (phammer_sema ctx, hammer::ast::expressions_t* args);
static const hammer::ast::expression*	expression    (phammer_sema ctx);
static void	list_of    (phammer_sema ctx, hammer::ast::expressions_t* args);
static const hammer::ast::expression*	list_of_impl    (phammer_sema ctx);
static const hammer::ast::expression*	path_like_seq    (phammer_sema ctx);
static void	path_like_seq_impl    (phammer_sema ctx, std::pair<pANTLR3_COMMON_TOKEN, pANTLR3_COMMON_TOKEN>* bounds);
static void	hammer_semaFree(phammer_sema ctx);
/* For use in tree output where we are accumulating rule labels via label += ruleRef
 * we need a function that knows how to free a return scope when the list is destroyed. 
 * We cannot just use ANTLR3_FREE because in debug tracking mode, this is a macro.
 */
static	void ANTLR3_CDECL freeScope(void * scope)
{
    ANTLR3_FREE(scope);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "hammer_sema.gt";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}
/** \brief Create a new hammer_sema parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API phammer_sema
hammer_semaNew   (pANTLR3_COMMON_TREE_NODE_STREAM instream)
{
	// See if we can create a new parser with the standard constructor
	//
	return hammer_semaNewSSD(instream, NULL);
}

/** \brief Create a new hammer_sema parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API phammer_sema
hammer_semaNewSSD   (pANTLR3_COMMON_TREE_NODE_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    phammer_sema ctx;	    /* Context structure we will build and return   */
    
    ctx	= (phammer_sema) ANTLR3_CALLOC(1, sizeof(hammer_sema));
    
    if	(ctx == NULL)
    {
		// Failed to allocate memory for parser context
		//
        return  NULL;
    }
    
    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * the base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 parser function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function. 
     *
     * We don't use the macros defined in hammer_sema.h here, in order that you can get a sense
     * of what goes where.
     */

    /* Create a base Tree parser/recognizer, using the supplied tree node stream
     */
    ctx->pTreeParser		= antlr3TreeParserNewStream(ANTLR3_SIZE_HINT, instream, state);
    /* Install the implementation of our hammer_sema interface
     */
    ctx->hamfile	= hamfile;
    ctx->project_def	= project_def;
    ctx->arguments	= arguments;
    ctx->expression	= expression;
    ctx->list_of	= list_of;
    ctx->list_of_impl	= list_of_impl;
    ctx->path_like_seq	= path_like_seq;
    ctx->path_like_seq_impl	= path_like_seq_impl;
    ctx->free			= hammer_semaFree;
    ctx->getGrammarFileName	= getGrammarFileName;
    
    /* Install the scope pushing methods.
     */

        
    

	
    /* Install the token table
     */
    PSRSTATE->tokenNames   = hammer_semaTokenNames;
    
    
    /* Return the newly built parser to the caller
     */
    return  ctx;
}

/** Free the parser resources
 */
 static void
 hammer_semaFree(phammer_sema ctx)
 {
    /* Free any scope memory
     */
    
        
	// Free this parser
	//
    ctx->pTreeParser->free(ctx->pTreeParser);
    ANTLR3_FREE(ctx);

    /* Everything is released, so we can return
     */
    return;
 }
 
/** Return token names used by this tree parser
 *
 * The returned pointer is used as an index into the token names table (using the token 
 * number as the index).
 * 
 * \return Pointer to first char * in the table.
 */
static pANTLR3_UINT8    *getTokenNames() 
{
        return hammer_semaTokenNames; 
}

    
/* Declare the bitsets
 */

/** Bitset defining follow set for error recovery in rule state: FOLLOW_HAMFILE_in_hamfile83  */
static	ANTLR3_BITWORD FOLLOW_HAMFILE_in_hamfile83_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000004) };
static  ANTLR3_BITSET_LIST FOLLOW_HAMFILE_in_hamfile83	= { FOLLOW_HAMFILE_in_hamfile83_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_project_def_in_hamfile85  */
static	ANTLR3_BITWORD FOLLOW_project_def_in_hamfile85_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000008) };
static  ANTLR3_BITSET_LIST FOLLOW_project_def_in_hamfile85	= { FOLLOW_project_def_in_hamfile85_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_IMPLICIT_PROJECT_DEF_in_project_def129  */
static	ANTLR3_BITWORD FOLLOW_IMPLICIT_PROJECT_DEF_in_project_def129_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_IMPLICIT_PROJECT_DEF_in_project_def129	= { FOLLOW_IMPLICIT_PROJECT_DEF_in_project_def129_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_EXPLICIT_PROJECT_DEF_in_project_def144  */
static	ANTLR3_BITWORD FOLLOW_EXPLICIT_PROJECT_DEF_in_project_def144_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000004) };
static  ANTLR3_BITSET_LIST FOLLOW_EXPLICIT_PROJECT_DEF_in_project_def144	= { FOLLOW_EXPLICIT_PROJECT_DEF_in_project_def144_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_26_in_project_def148  */
static	ANTLR3_BITWORD FOLLOW_26_in_project_def148_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000400) };
static  ANTLR3_BITSET_LIST FOLLOW_26_in_project_def148	= { FOLLOW_26_in_project_def148_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_arguments_in_project_def150  */
static	ANTLR3_BITWORD FOLLOW_arguments_in_project_def150_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000008) };
static  ANTLR3_BITSET_LIST FOLLOW_arguments_in_project_def150	= { FOLLOW_arguments_in_project_def150_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ARGUMENTS_in_arguments183  */
static	ANTLR3_BITWORD FOLLOW_ARGUMENTS_in_arguments183_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000004) };
static  ANTLR3_BITSET_LIST FOLLOW_ARGUMENTS_in_arguments183	= { FOLLOW_ARGUMENTS_in_arguments183_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expression_in_arguments186  */
static	ANTLR3_BITWORD FOLLOW_expression_in_arguments186_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000003008) };
static  ANTLR3_BITSET_LIST FOLLOW_expression_in_arguments186	= { FOLLOW_expression_in_arguments186_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_EMPTY_EXPRESSION_in_expression218  */
static	ANTLR3_BITWORD FOLLOW_EMPTY_EXPRESSION_in_expression218_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_EMPTY_EXPRESSION_in_expression218	= { FOLLOW_EMPTY_EXPRESSION_in_expression218_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_list_of_in_expression232  */
static	ANTLR3_BITWORD FOLLOW_list_of_in_expression232_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_list_of_in_expression232	= { FOLLOW_list_of_in_expression232_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_LIST_OF_in_list_of255  */
static	ANTLR3_BITWORD FOLLOW_LIST_OF_in_list_of255_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000004) };
static  ANTLR3_BITSET_LIST FOLLOW_LIST_OF_in_list_of255	= { FOLLOW_LIST_OF_in_list_of255_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_list_of_impl_in_list_of258  */
static	ANTLR3_BITWORD FOLLOW_list_of_impl_in_list_of258_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000004008) };
static  ANTLR3_BITSET_LIST FOLLOW_list_of_impl_in_list_of258	= { FOLLOW_list_of_impl_in_list_of258_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_path_like_seq_in_list_of_impl290  */
static	ANTLR3_BITWORD FOLLOW_path_like_seq_in_list_of_impl290_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_path_like_seq_in_list_of_impl290	= { FOLLOW_path_like_seq_in_list_of_impl290_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_PATH_LIKE_SEQ_in_path_like_seq313  */
static	ANTLR3_BITWORD FOLLOW_PATH_LIKE_SEQ_in_path_like_seq313_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000004) };
static  ANTLR3_BITSET_LIST FOLLOW_PATH_LIKE_SEQ_in_path_like_seq313	= { FOLLOW_PATH_LIKE_SEQ_in_path_like_seq313_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_SLASH_in_path_like_seq315  */
static	ANTLR3_BITWORD FOLLOW_SLASH_in_path_like_seq315_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000100000) };
static  ANTLR3_BITSET_LIST FOLLOW_SLASH_in_path_like_seq315	= { FOLLOW_SLASH_in_path_like_seq315_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_path_like_seq_impl_in_path_like_seq317  */
static	ANTLR3_BITWORD FOLLOW_path_like_seq_impl_in_path_like_seq317_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000008) };
static  ANTLR3_BITSET_LIST FOLLOW_path_like_seq_impl_in_path_like_seq317	= { FOLLOW_path_like_seq_impl_in_path_like_seq317_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_PATH_LIKE_SEQ_in_path_like_seq327  */
static	ANTLR3_BITWORD FOLLOW_PATH_LIKE_SEQ_in_path_like_seq327_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000004) };
static  ANTLR3_BITSET_LIST FOLLOW_PATH_LIKE_SEQ_in_path_like_seq327	= { FOLLOW_PATH_LIKE_SEQ_in_path_like_seq327_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_path_like_seq_impl_in_path_like_seq329  */
static	ANTLR3_BITWORD FOLLOW_path_like_seq_impl_in_path_like_seq329_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000008) };
static  ANTLR3_BITSET_LIST FOLLOW_path_like_seq_impl_in_path_like_seq329	= { FOLLOW_path_like_seq_impl_in_path_like_seq329_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ID_in_path_like_seq_impl353  */
static	ANTLR3_BITWORD FOLLOW_ID_in_path_like_seq_impl353_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_ID_in_path_like_seq_impl353	= { FOLLOW_ID_in_path_like_seq_impl353_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ID_in_path_like_seq_impl362  */
static	ANTLR3_BITWORD FOLLOW_ID_in_path_like_seq_impl362_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000100000) };
static  ANTLR3_BITSET_LIST FOLLOW_ID_in_path_like_seq_impl362	= { FOLLOW_ID_in_path_like_seq_impl362_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ID_in_path_like_seq_impl364  */
static	ANTLR3_BITWORD FOLLOW_ID_in_path_like_seq_impl364_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000100000) };
static  ANTLR3_BITSET_LIST FOLLOW_ID_in_path_like_seq_impl364	= { FOLLOW_ID_in_path_like_seq_impl364_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ID_in_path_like_seq_impl369  */
static	ANTLR3_BITWORD FOLLOW_ID_in_path_like_seq_impl369_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_ID_in_path_like_seq_impl369	= { FOLLOW_ID_in_path_like_seq_impl369_bits, 1	};
     

 
 
/* ==============================================
 * Parsing rules
 */
/** 
 * $ANTLR start hamfile
 * hammer_sema.gt:17:1: hamfile returns [const hammer::ast::hamfile* result] : ^( HAMFILE project_def ) ;
 */
static const hammer::ast::hamfile*
hamfile(phammer_sema ctx)
{   
    const hammer::ast::hamfile* result = NULL;

    const hammer::ast::project_def* project_def1;
    #undef	RETURN_TYPE_project_def1
    #define	RETURN_TYPE_project_def1 const hammer::ast::project_def*

    /* Initialize rule variables
     */


    project_def1 = NULL;

    {
        // hammer_sema.gt:18:9: ( ^( HAMFILE project_def ) )
        // hammer_sema.gt:18:11: ^( HAMFILE project_def )
        {
             MATCHT(HAMFILE, &FOLLOW_HAMFILE_in_hamfile83); 
            if  (HASEXCEPTION())
            {
                goto rulehamfileEx;
            }


            MATCHT(ANTLR3_TOKEN_DOWN, NULL); 
            if  (HASEXCEPTION())
            {
                goto rulehamfileEx;
            }

            FOLLOWPUSH(FOLLOW_project_def_in_hamfile85);
            project_def1=project_def(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulehamfileEx;
            }


            MATCHT(ANTLR3_TOKEN_UP, NULL); 
            if  (HASEXCEPTION())
            {
                goto rulehamfileEx;
            }

            {
                 result = SEMA->on_hamfile(project_def1); 
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulehamfileEx; /* Prevent compiler warnings */
    rulehamfileEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return result;
}
/* $ANTLR end hamfile */

/** 
 * $ANTLR start project_def
 * hammer_sema.gt:21:1: project_def returns [const hammer::ast::project_def* result] : ( IMPLICIT_PROJECT_DEF | ^( EXPLICIT_PROJECT_DEF p= 'project' arguments[&args] ) );
 */
static const hammer::ast::project_def*
project_def(phammer_sema ctx)
{   
    const hammer::ast::project_def* result = NULL;

    pANTLR3_BASE_TREE    p;

    /* Initialize rule variables
     */


     hammer::ast::expressions_t args; 
    p       = NULL;

    {
        {
            //  hammer_sema.gt:23:9: ( IMPLICIT_PROJECT_DEF | ^( EXPLICIT_PROJECT_DEF p= 'project' arguments[&args] ) )
            
            ANTLR3_UINT32 alt1;

            alt1=2;


            {
                int LA1_0 = LA(1);
                if ( (LA1_0 == IMPLICIT_PROJECT_DEF) ) 
                {
                    alt1=1;
                }
                else if ( (LA1_0 == EXPLICIT_PROJECT_DEF) ) 
                {
                    alt1=2;
                }
                else 
                {
                
                    CONSTRUCTEX();
                    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                    EXCEPTION->message      = (void *)"";
                    EXCEPTION->decisionNum  = 1;
                    EXCEPTION->state        = 0;


                    goto ruleproject_defEx;
                }
            }
            switch (alt1) 
            {
        	case 1:
        	    // hammer_sema.gt:23:11: IMPLICIT_PROJECT_DEF
        	    {
        	         MATCHT(IMPLICIT_PROJECT_DEF, &FOLLOW_IMPLICIT_PROJECT_DEF_in_project_def129); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleproject_defEx;
        	        }

        	        {
        	             result = SEMA->on_implicit_project_def(); 
        	        }

        	    }
        	    break;
        	case 2:
        	    // hammer_sema.gt:24:11: ^( EXPLICIT_PROJECT_DEF p= 'project' arguments[&args] )
        	    {
        	         MATCHT(EXPLICIT_PROJECT_DEF, &FOLLOW_EXPLICIT_PROJECT_DEF_in_project_def144); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleproject_defEx;
        	        }


        	        MATCHT(ANTLR3_TOKEN_DOWN, NULL); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleproject_defEx;
        	        }

        	        p = (pANTLR3_BASE_TREE) MATCHT(26, &FOLLOW_26_in_project_def148); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleproject_defEx;
        	        }

        	        FOLLOWPUSH(FOLLOW_arguments_in_project_def150);
        	        arguments(ctx, &args);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleproject_defEx;
        	        }


        	        MATCHT(ANTLR3_TOKEN_UP, NULL); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleproject_defEx;
        	        }

        	        {
        	             result = SEMA->on_explicit_project_def(p->getToken(p), args); 
        	        }

        	    }
        	    break;

            }
        }
    }
    

    // This is where rules clean up and exit
    //
    goto ruleproject_defEx; /* Prevent compiler warnings */
    ruleproject_defEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return result;
}
/* $ANTLR end project_def */

/** 
 * $ANTLR start arguments
 * hammer_sema.gt:29:1: arguments[hammer::ast::expressions_t* args] : ^( ARGUMENTS ( expression )* ) ;
 */
static void
arguments(phammer_sema ctx, hammer::ast::expressions_t* args)
{   
    const hammer::ast::expression* expression2;
    #undef	RETURN_TYPE_expression2
    #define	RETURN_TYPE_expression2 const hammer::ast::expression*

    /* Initialize rule variables
     */


    expression2 = NULL;

    {
        // hammer_sema.gt:30:9: ( ^( ARGUMENTS ( expression )* ) )
        // hammer_sema.gt:30:11: ^( ARGUMENTS ( expression )* )
        {
             MATCHT(ARGUMENTS, &FOLLOW_ARGUMENTS_in_arguments183); 
            if  (HASEXCEPTION())
            {
                goto ruleargumentsEx;
            }


            if ( LA(1)==ANTLR3_TOKEN_DOWN ) {
                MATCHT(ANTLR3_TOKEN_DOWN, NULL); 
                if  (HASEXCEPTION())
                {
                    goto ruleargumentsEx;
                }


                // hammer_sema.gt:30:23: ( expression )*

                for (;;)
                {
                    int alt2=2;
                    {
                       /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                        */
                        int LA2_0 = LA(1);
                        if ( (((LA2_0 >= EMPTY_EXPRESSION) && (LA2_0 <= LIST_OF))) ) 
                        {
                            alt2=1;
                        }

                    }
                    switch (alt2) 
                    {
                	case 1:
                	    // hammer_sema.gt:30:24: expression
                	    {
                	        FOLLOWPUSH(FOLLOW_expression_in_arguments186);
                	        expression2=expression(ctx);

                	        FOLLOWPOP();
                	        if  (HASEXCEPTION())
                	        {
                	            goto ruleargumentsEx;
                	        }

                	        {
                	             args->push_back(expression2); 
                	        }

                	    }
                	    break;

                	default:
                	    goto loop2;	/* break out of the loop */
                	    break;
                    }
                }
                loop2: ; /* Jump out to here if this rule does not match */


                MATCHT(ANTLR3_TOKEN_UP, NULL); 
                if  (HASEXCEPTION())
                {
                    goto ruleargumentsEx;
                }

            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleargumentsEx; /* Prevent compiler warnings */
    ruleargumentsEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return ;
}
/* $ANTLR end arguments */

/** 
 * $ANTLR start expression
 * hammer_sema.gt:33:1: expression returns [const hammer::ast::expression* result] : ( EMPTY_EXPRESSION | list_of[&args] );
 */
static const hammer::ast::expression*
expression(phammer_sema ctx)
{   
    const hammer::ast::expression* result = NULL;

    /* Initialize rule variables
     */


     hammer::ast::expressions_t args; 
    {
        {
            //  hammer_sema.gt:35:2: ( EMPTY_EXPRESSION | list_of[&args] )
            
            ANTLR3_UINT32 alt3;

            alt3=2;


            {
                int LA3_0 = LA(1);
                if ( (LA3_0 == EMPTY_EXPRESSION) ) 
                {
                    alt3=1;
                }
                else if ( (LA3_0 == LIST_OF) ) 
                {
                    alt3=2;
                }
                else 
                {
                
                    CONSTRUCTEX();
                    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                    EXCEPTION->message      = (void *)"";
                    EXCEPTION->decisionNum  = 3;
                    EXCEPTION->state        = 0;


                    goto ruleexpressionEx;
                }
            }
            switch (alt3) 
            {
        	case 1:
        	    // hammer_sema.gt:35:4: EMPTY_EXPRESSION
        	    {
        	         MATCHT(EMPTY_EXPRESSION, &FOLLOW_EMPTY_EXPRESSION_in_expression218); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexpressionEx;
        	        }

        	        {
        	             result = SEMA->on_empty_expr(); 
        	        }

        	    }
        	    break;
        	case 2:
        	    // hammer_sema.gt:36:11: list_of[&args]
        	    {
        	        FOLLOWPUSH(FOLLOW_list_of_in_expression232);
        	        list_of(ctx, &args);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexpressionEx;
        	        }

        	        {
        	             result = SEMA->on_list_of(args); 
        	        }

        	    }
        	    break;

            }
        }
    }
    

    // This is where rules clean up and exit
    //
    goto ruleexpressionEx; /* Prevent compiler warnings */
    ruleexpressionEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return result;
}
/* $ANTLR end expression */

/** 
 * $ANTLR start list_of
 * hammer_sema.gt:39:1: list_of[hammer::ast::expressions_t* args] : ^( LIST_OF ( list_of_impl )+ ) ;
 */
static void
list_of(phammer_sema ctx, hammer::ast::expressions_t* args)
{   
    const hammer::ast::expression* list_of_impl3;
    #undef	RETURN_TYPE_list_of_impl3
    #define	RETURN_TYPE_list_of_impl3 const hammer::ast::expression*

    /* Initialize rule variables
     */


    list_of_impl3 = NULL;

    {
        // hammer_sema.gt:40:2: ( ^( LIST_OF ( list_of_impl )+ ) )
        // hammer_sema.gt:40:4: ^( LIST_OF ( list_of_impl )+ )
        {
             MATCHT(LIST_OF, &FOLLOW_LIST_OF_in_list_of255); 
            if  (HASEXCEPTION())
            {
                goto rulelist_ofEx;
            }


            MATCHT(ANTLR3_TOKEN_DOWN, NULL); 
            if  (HASEXCEPTION())
            {
                goto rulelist_ofEx;
            }

            // hammer_sema.gt:40:14: ( list_of_impl )+
            {
                int cnt4=0;

                for (;;)
                {
                    int alt4=2;
            	{
            	   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
            	    */
            	    int LA4_0 = LA(1);
            	    if ( (LA4_0 == PATH_LIKE_SEQ) ) 
            	    {
            	        alt4=1;
            	    }

            	}
            	switch (alt4) 
            	{
            	    case 1:
            	        // hammer_sema.gt:40:15: list_of_impl
            	        {
            	            FOLLOWPUSH(FOLLOW_list_of_impl_in_list_of258);
            	            list_of_impl3=list_of_impl(ctx);

            	            FOLLOWPOP();
            	            if  (HASEXCEPTION())
            	            {
            	                goto rulelist_ofEx;
            	            }

            	            {
            	                 args->push_back(list_of_impl3); 
            	            }

            	        }
            	        break;

            	    default:
            	    
            		if ( cnt4 >= 1 )
            		{
            		    goto loop4;
            		}
            		/* mismatchedSetEx()
            		 */
            		CONSTRUCTEX();
            		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
            		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


            		goto rulelist_ofEx;
            	}
            	cnt4++;
                }
                loop4: ;	/* Jump to here if this rule does not match */
            }

            MATCHT(ANTLR3_TOKEN_UP, NULL); 
            if  (HASEXCEPTION())
            {
                goto rulelist_ofEx;
            }


        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulelist_ofEx; /* Prevent compiler warnings */
    rulelist_ofEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return ;
}
/* $ANTLR end list_of */

/** 
 * $ANTLR start list_of_impl
 * hammer_sema.gt:43:1: list_of_impl returns [const hammer::ast::expression* result ] : path_like_seq ;
 */
static const hammer::ast::expression*
list_of_impl(phammer_sema ctx)
{   
    const hammer::ast::expression* result = NULL;

    const hammer::ast::expression* path_like_seq4;
    #undef	RETURN_TYPE_path_like_seq4
    #define	RETURN_TYPE_path_like_seq4 const hammer::ast::expression*

    /* Initialize rule variables
     */


    path_like_seq4 = NULL;

    {
        // hammer_sema.gt:44:2: ( path_like_seq )
        // hammer_sema.gt:44:4: path_like_seq
        {
            FOLLOWPUSH(FOLLOW_path_like_seq_in_list_of_impl290);
            path_like_seq4=path_like_seq(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulelist_of_implEx;
            }

            {
                 result = path_like_seq4; 
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulelist_of_implEx; /* Prevent compiler warnings */
    rulelist_of_implEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return result;
}
/* $ANTLR end list_of_impl */

/** 
 * $ANTLR start path_like_seq
 * hammer_sema.gt:47:1: path_like_seq returns [const hammer::ast::expression* result] : ( ^( PATH_LIKE_SEQ SLASH path_like_seq_impl[&bounds] ) | ^( PATH_LIKE_SEQ path_like_seq_impl[&bounds] ) );
 */
static const hammer::ast::expression*
path_like_seq(phammer_sema ctx)
{   
    const hammer::ast::expression* result = NULL;

    pANTLR3_BASE_TREE    SLASH5;

    /* Initialize rule variables
     */


     std::pair<pANTLR3_COMMON_TOKEN, pANTLR3_COMMON_TOKEN> bounds; 
    SLASH5       = NULL;

    {
        {
            //  hammer_sema.gt:49:2: ( ^( PATH_LIKE_SEQ SLASH path_like_seq_impl[&bounds] ) | ^( PATH_LIKE_SEQ path_like_seq_impl[&bounds] ) )
            
            ANTLR3_UINT32 alt5;

            alt5=2;


            {
                int LA5_0 = LA(1);
                if ( (LA5_0 == PATH_LIKE_SEQ) ) 
                {

                    {
                        int LA5_1 = LA(2);
                        if ( (LA5_1 == DOWN) ) 
                        {

                            {
                                int LA5_2 = LA(3);
                                if ( (LA5_2 == SLASH) ) 
                                {
                                    alt5=1;
                                }
                                else if ( (LA5_2 == ID) ) 
                                {
                                    alt5=2;
                                }
                                else 
                                {
                                
                                    CONSTRUCTEX();
                                    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                                    EXCEPTION->message      = (void *)"";
                                    EXCEPTION->decisionNum  = 5;
                                    EXCEPTION->state        = 2;


                                    goto rulepath_like_seqEx;
                                }
                            }
                        }
                        else 
                        {
                        
                            CONSTRUCTEX();
                            EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                            EXCEPTION->message      = (void *)"";
                            EXCEPTION->decisionNum  = 5;
                            EXCEPTION->state        = 1;


                            goto rulepath_like_seqEx;
                        }
                    }
                }
                else 
                {
                
                    CONSTRUCTEX();
                    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                    EXCEPTION->message      = (void *)"";
                    EXCEPTION->decisionNum  = 5;
                    EXCEPTION->state        = 0;


                    goto rulepath_like_seqEx;
                }
            }
            switch (alt5) 
            {
        	case 1:
        	    // hammer_sema.gt:49:4: ^( PATH_LIKE_SEQ SLASH path_like_seq_impl[&bounds] )
        	    {
        	         MATCHT(PATH_LIKE_SEQ, &FOLLOW_PATH_LIKE_SEQ_in_path_like_seq313); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulepath_like_seqEx;
        	        }


        	        MATCHT(ANTLR3_TOKEN_DOWN, NULL); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulepath_like_seqEx;
        	        }

        	        SLASH5 = (pANTLR3_BASE_TREE) MATCHT(SLASH, &FOLLOW_SLASH_in_path_like_seq315); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulepath_like_seqEx;
        	        }

        	        FOLLOWPUSH(FOLLOW_path_like_seq_impl_in_path_like_seq317);
        	        path_like_seq_impl(ctx, &bounds);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulepath_like_seqEx;
        	        }


        	        MATCHT(ANTLR3_TOKEN_UP, NULL); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulepath_like_seqEx;
        	        }

        	        {
        	             result = SEMA->on_path_like_seq(SLASH5->getToken(SLASH5), bounds.second); 
        	        }

        	    }
        	    break;
        	case 2:
        	    // hammer_sema.gt:50:4: ^( PATH_LIKE_SEQ path_like_seq_impl[&bounds] )
        	    {
        	         MATCHT(PATH_LIKE_SEQ, &FOLLOW_PATH_LIKE_SEQ_in_path_like_seq327); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulepath_like_seqEx;
        	        }


        	        MATCHT(ANTLR3_TOKEN_DOWN, NULL); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulepath_like_seqEx;
        	        }

        	        FOLLOWPUSH(FOLLOW_path_like_seq_impl_in_path_like_seq329);
        	        path_like_seq_impl(ctx, &bounds);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulepath_like_seqEx;
        	        }


        	        MATCHT(ANTLR3_TOKEN_UP, NULL); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulepath_like_seqEx;
        	        }

        	        {
        	             result = SEMA->on_path_like_seq(bounds.first, bounds.second); 
        	        }

        	    }
        	    break;

            }
        }
    }
    

    // This is where rules clean up and exit
    //
    goto rulepath_like_seqEx; /* Prevent compiler warnings */
    rulepath_like_seqEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return result;
}
/* $ANTLR end path_like_seq */

/** 
 * $ANTLR start path_like_seq_impl
 * hammer_sema.gt:53:1: path_like_seq_impl[std::pair<pANTLR3_COMMON_TOKEN, pANTLR3_COMMON_TOKEN>* bounds] : ( ID | first= ID ( ID )* last= ID );
 */
static void
path_like_seq_impl(phammer_sema ctx, std::pair<pANTLR3_COMMON_TOKEN, pANTLR3_COMMON_TOKEN>* bounds)
{   
    pANTLR3_BASE_TREE    first;
    pANTLR3_BASE_TREE    last;
    pANTLR3_BASE_TREE    ID6;

    /* Initialize rule variables
     */


    first       = NULL;
    last       = NULL;
    ID6       = NULL;

    {
        {
            //  hammer_sema.gt:54:2: ( ID | first= ID ( ID )* last= ID )
            
            ANTLR3_UINT32 alt7;

            alt7=2;


            {
                int LA7_0 = LA(1);
                if ( (LA7_0 == ID) ) 
                {

                    {
                        int LA7_1 = LA(2);
                        if ( (LA7_1 == UP) ) 
                        {
                            alt7=1;
                        }
                        else if ( (LA7_1 == ID) ) 
                        {
                            alt7=2;
                        }
                        else 
                        {
                        
                            CONSTRUCTEX();
                            EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                            EXCEPTION->message      = (void *)"";
                            EXCEPTION->decisionNum  = 7;
                            EXCEPTION->state        = 1;


                            goto rulepath_like_seq_implEx;
                        }
                    }
                }
                else 
                {
                
                    CONSTRUCTEX();
                    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                    EXCEPTION->message      = (void *)"";
                    EXCEPTION->decisionNum  = 7;
                    EXCEPTION->state        = 0;


                    goto rulepath_like_seq_implEx;
                }
            }
            switch (alt7) 
            {
        	case 1:
        	    // hammer_sema.gt:54:4: ID
        	    {
        	        ID6 = (pANTLR3_BASE_TREE) MATCHT(ID, &FOLLOW_ID_in_path_like_seq_impl353); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulepath_like_seq_implEx;
        	        }

        	        {
        	             bounds->first = bounds->second = ID6->getToken(ID6); 
        	        }

        	    }
        	    break;
        	case 2:
        	    // hammer_sema.gt:55:4: first= ID ( ID )* last= ID
        	    {
        	        first = (pANTLR3_BASE_TREE) MATCHT(ID, &FOLLOW_ID_in_path_like_seq_impl362); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulepath_like_seq_implEx;
        	        }


        	        // hammer_sema.gt:55:13: ( ID )*

        	        for (;;)
        	        {
        	            int alt6=2;
        	            {
        	               /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
        	                */
        	                int LA6_0 = LA(1);
        	                if ( (LA6_0 == ID) ) 
        	                {
        	                    {
        	                       /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
        	                        */
        	                        int LA6_1 = LA(2);
        	                        if ( (LA6_1 == ID) ) 
        	                        {
        	                            alt6=1;
        	                        }

        	                    }
        	                }

        	            }
        	            switch (alt6) 
        	            {
        	        	case 1:
        	        	    // hammer_sema.gt:55:13: ID
        	        	    {
        	        	         MATCHT(ID, &FOLLOW_ID_in_path_like_seq_impl364); 
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto rulepath_like_seq_implEx;
        	        	        }


        	        	    }
        	        	    break;

        	        	default:
        	        	    goto loop6;	/* break out of the loop */
        	        	    break;
        	            }
        	        }
        	        loop6: ; /* Jump out to here if this rule does not match */

        	        last = (pANTLR3_BASE_TREE) MATCHT(ID, &FOLLOW_ID_in_path_like_seq_impl369); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulepath_like_seq_implEx;
        	        }

        	        {
        	             bounds->first = first->getToken(first); bounds->second = last->getToken(last); 
        	        }

        	    }
        	    break;

            }
        }
    }
    

    // This is where rules clean up and exit
    //
    goto rulepath_like_seq_implEx; /* Prevent compiler warnings */
    rulepath_like_seq_implEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return ;
}
/* $ANTLR end path_like_seq_impl */
/* End of parsing rules
 * ==============================================
 */

/* ==============================================
 * Syntactic predicates
 */
/* End of syntactic predicates
 * ==============================================
 */

 
 



/* End of code
 * =============================================================================
 */
